// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.blemobi.sep.probuf.nano;

@SuppressWarnings("hiding")
public interface AccountProtos {

  // enum ELevelType
  public static final int User = 0;
  public static final int Vip = 1;
  public static final int Vipp = 2;
  public static final int Vo = 3;
  public static final int Tourist = 4;

  // enum ERightId
  public static final int weibo_show_left_catalog = 0;
  public static final int weibo_show_top_dropdown = 1;
  public static final int weibo_show_icon = 2;
  public static final int weibo_show_comment = 3;
  public static final int weibo_show_collect = 4;
  public static final int weibo_show_more = 5;
  public static final int weibo_show_view_details = 6;
  public static final int weibo_comment_text = 7;
  public static final int weibo_comment_audio = 8;
  public static final int weibo_post_text = 9;
  public static final int weibo_post_image = 10;
  public static final int weibo_post_video = 11;
  public static final int weibo_post_audio = 12;
  public static final int personal_record_external_links = 13;
  public static final int personal_record_icon = 14;
  public static final int personal_record_community = 15;
  public static final int personal_record_video_classify_page = 16;
  public static final int personal_record_audio_classify_page = 17;
  public static final int friend_system_recommend = 18;
  public static final int friend_system_search = 19;
  public static final int friend_system_friend_apply_for = 20;
  public static final int friend_system_address_book = 21;
  public static final int friend_system_friend = 22;
  public static final int friend_system_my_apply_for = 23;
  public static final int real_name = 24;

  public static final class PUserList extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PUserList[] _emptyArray;
    public static PUserList[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PUserList[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .common.PUser list = 1;
    public com.blemobi.sep.probuf.nano.AccountProtos.PUser[] list;

    public PUserList() {
      clear();
    }

    public PUserList clear() {
      list = com.blemobi.sep.probuf.nano.AccountProtos.PUser.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.AccountProtos.PUser element = this.list[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.AccountProtos.PUser element = this.list[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public PUserList mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.list == null ? 0 : this.list.length;
            com.blemobi.sep.probuf.nano.AccountProtos.PUser[] newArray =
                new com.blemobi.sep.probuf.nano.AccountProtos.PUser[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.list, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.AccountProtos.PUser();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.AccountProtos.PUser();
            input.readMessage(newArray[i]);
            this.list = newArray;
            break;
          }
        }
      }
    }

    public static PUserList parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PUserList(), data);
    }

    public static PUserList parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PUserList().mergeFrom(input);
    }
  }

  public static final class PUser extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PUser[] _emptyArray;
    public static PUser[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PUser[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string uuid = 6;
    public java.lang.String uuid;

    // optional string password = 7;
    public java.lang.String password;

    // optional string username = 8;
    public java.lang.String username;

    // optional string nickname = 9;
    public java.lang.String nickname;

    // optional string headImgURL = 10;
    public java.lang.String headImgURL;

    // optional string realname = 11;
    public java.lang.String realname;

    // optional int32 gender = 12;
    public int gender;

    // optional string email = 13;
    public java.lang.String email;

    // optional string birthday = 14;
    public java.lang.String birthday;

    // optional string cellphone = 15;
    public java.lang.String cellphone;

    // optional int32 timeZone = 16;
    public int timeZone;

    // optional string locale = 17;
    public java.lang.String locale;

    // optional int32 membershipLevel = 18;
    public int membershipLevel;

    // optional int64 lastUpdateTime = 19;
    public long lastUpdateTime;

    // optional int64 lastLoginTime = 20;
    public long lastLoginTime;

    // optional string userResume = 21;
    public java.lang.String userResume;

    // optional string link1 = 22;
    public java.lang.String link1;

    // optional string link2 = 23;
    public java.lang.String link2;

    // optional string link3 = 24;
    public java.lang.String link3;

    // optional int64 chatId = 25;
    public long chatId;

    // optional .common.PLevelInfo levelInfo = 26;
    public com.blemobi.sep.probuf.nano.AccountProtos.PLevelInfo levelInfo;

    // optional bool disable = 27;
    public boolean disable;

    // optional bool isAI = 28;
    public boolean isAI;

    // optional bool forceChangePwd = 29;
    public boolean forceChangePwd;

    // optional string areaCode = 30;
    public java.lang.String areaCode;

    // optional string areaName = 31;
    public java.lang.String areaName;

    public PUser() {
      clear();
    }

    public PUser clear() {
      uuid = "";
      password = "";
      username = "";
      nickname = "";
      headImgURL = "";
      realname = "";
      gender = 0;
      email = "";
      birthday = "";
      cellphone = "";
      timeZone = 0;
      locale = "";
      membershipLevel = 0;
      lastUpdateTime = 0L;
      lastLoginTime = 0L;
      userResume = "";
      link1 = "";
      link2 = "";
      link3 = "";
      chatId = 0L;
      levelInfo = null;
      disable = false;
      isAI = false;
      forceChangePwd = false;
      areaCode = "";
      areaName = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.uuid.equals("")) {
        output.writeString(6, this.uuid);
      }
      if (!this.password.equals("")) {
        output.writeString(7, this.password);
      }
      if (!this.username.equals("")) {
        output.writeString(8, this.username);
      }
      if (!this.nickname.equals("")) {
        output.writeString(9, this.nickname);
      }
      if (!this.headImgURL.equals("")) {
        output.writeString(10, this.headImgURL);
      }
      if (!this.realname.equals("")) {
        output.writeString(11, this.realname);
      }
      if (this.gender != 0) {
        output.writeInt32(12, this.gender);
      }
      if (!this.email.equals("")) {
        output.writeString(13, this.email);
      }
      if (!this.birthday.equals("")) {
        output.writeString(14, this.birthday);
      }
      if (!this.cellphone.equals("")) {
        output.writeString(15, this.cellphone);
      }
      if (this.timeZone != 0) {
        output.writeInt32(16, this.timeZone);
      }
      if (!this.locale.equals("")) {
        output.writeString(17, this.locale);
      }
      if (this.membershipLevel != 0) {
        output.writeInt32(18, this.membershipLevel);
      }
      if (this.lastUpdateTime != 0L) {
        output.writeInt64(19, this.lastUpdateTime);
      }
      if (this.lastLoginTime != 0L) {
        output.writeInt64(20, this.lastLoginTime);
      }
      if (!this.userResume.equals("")) {
        output.writeString(21, this.userResume);
      }
      if (!this.link1.equals("")) {
        output.writeString(22, this.link1);
      }
      if (!this.link2.equals("")) {
        output.writeString(23, this.link2);
      }
      if (!this.link3.equals("")) {
        output.writeString(24, this.link3);
      }
      if (this.chatId != 0L) {
        output.writeInt64(25, this.chatId);
      }
      if (this.levelInfo != null) {
        output.writeMessage(26, this.levelInfo);
      }
      if (this.disable != false) {
        output.writeBool(27, this.disable);
      }
      if (this.isAI != false) {
        output.writeBool(28, this.isAI);
      }
      if (this.forceChangePwd != false) {
        output.writeBool(29, this.forceChangePwd);
      }
      if (!this.areaCode.equals("")) {
        output.writeString(30, this.areaCode);
      }
      if (!this.areaName.equals("")) {
        output.writeString(31, this.areaName);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.uuid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.uuid);
      }
      if (!this.password.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.password);
      }
      if (!this.username.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.username);
      }
      if (!this.nickname.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(9, this.nickname);
      }
      if (!this.headImgURL.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(10, this.headImgURL);
      }
      if (!this.realname.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(11, this.realname);
      }
      if (this.gender != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(12, this.gender);
      }
      if (!this.email.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(13, this.email);
      }
      if (!this.birthday.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(14, this.birthday);
      }
      if (!this.cellphone.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(15, this.cellphone);
      }
      if (this.timeZone != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(16, this.timeZone);
      }
      if (!this.locale.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(17, this.locale);
      }
      if (this.membershipLevel != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(18, this.membershipLevel);
      }
      if (this.lastUpdateTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(19, this.lastUpdateTime);
      }
      if (this.lastLoginTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(20, this.lastLoginTime);
      }
      if (!this.userResume.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(21, this.userResume);
      }
      if (!this.link1.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(22, this.link1);
      }
      if (!this.link2.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(23, this.link2);
      }
      if (!this.link3.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(24, this.link3);
      }
      if (this.chatId != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(25, this.chatId);
      }
      if (this.levelInfo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(26, this.levelInfo);
      }
      if (this.disable != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(27, this.disable);
      }
      if (this.isAI != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(28, this.isAI);
      }
      if (this.forceChangePwd != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(29, this.forceChangePwd);
      }
      if (!this.areaCode.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(30, this.areaCode);
      }
      if (!this.areaName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(31, this.areaName);
      }
      return size;
    }

    @Override
    public PUser mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 50: {
            this.uuid = input.readString();
            break;
          }
          case 58: {
            this.password = input.readString();
            break;
          }
          case 66: {
            this.username = input.readString();
            break;
          }
          case 74: {
            this.nickname = input.readString();
            break;
          }
          case 82: {
            this.headImgURL = input.readString();
            break;
          }
          case 90: {
            this.realname = input.readString();
            break;
          }
          case 96: {
            this.gender = input.readInt32();
            break;
          }
          case 106: {
            this.email = input.readString();
            break;
          }
          case 114: {
            this.birthday = input.readString();
            break;
          }
          case 122: {
            this.cellphone = input.readString();
            break;
          }
          case 128: {
            this.timeZone = input.readInt32();
            break;
          }
          case 138: {
            this.locale = input.readString();
            break;
          }
          case 144: {
            this.membershipLevel = input.readInt32();
            break;
          }
          case 152: {
            this.lastUpdateTime = input.readInt64();
            break;
          }
          case 160: {
            this.lastLoginTime = input.readInt64();
            break;
          }
          case 170: {
            this.userResume = input.readString();
            break;
          }
          case 178: {
            this.link1 = input.readString();
            break;
          }
          case 186: {
            this.link2 = input.readString();
            break;
          }
          case 194: {
            this.link3 = input.readString();
            break;
          }
          case 200: {
            this.chatId = input.readInt64();
            break;
          }
          case 210: {
            if (this.levelInfo == null) {
              this.levelInfo = new com.blemobi.sep.probuf.nano.AccountProtos.PLevelInfo();
            }
            input.readMessage(this.levelInfo);
            break;
          }
          case 216: {
            this.disable = input.readBool();
            break;
          }
          case 224: {
            this.isAI = input.readBool();
            break;
          }
          case 232: {
            this.forceChangePwd = input.readBool();
            break;
          }
          case 242: {
            this.areaCode = input.readString();
            break;
          }
          case 250: {
            this.areaName = input.readString();
            break;
          }
        }
      }
    }

    public static PUser parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PUser(), data);
    }

    public static PUser parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PUser().mergeFrom(input);
    }
  }

  public static final class PUserListEx extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PUserListEx[] _emptyArray;
    public static PUserListEx[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PUserListEx[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .common.PUserEx list = 1;
    public com.blemobi.sep.probuf.nano.AccountProtos.PUserEx[] list;

    public PUserListEx() {
      clear();
    }

    public PUserListEx clear() {
      list = com.blemobi.sep.probuf.nano.AccountProtos.PUserEx.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.AccountProtos.PUserEx element = this.list[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.AccountProtos.PUserEx element = this.list[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public PUserListEx mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.list == null ? 0 : this.list.length;
            com.blemobi.sep.probuf.nano.AccountProtos.PUserEx[] newArray =
                new com.blemobi.sep.probuf.nano.AccountProtos.PUserEx[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.list, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.AccountProtos.PUserEx();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.AccountProtos.PUserEx();
            input.readMessage(newArray[i]);
            this.list = newArray;
            break;
          }
        }
      }
    }

    public static PUserListEx parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PUserListEx(), data);
    }

    public static PUserListEx parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PUserListEx().mergeFrom(input);
    }
  }

  public static final class PUserEx extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PUserEx[] _emptyArray;
    public static PUserEx[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PUserEx[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string uuid = 6;
    public java.lang.String uuid;

    // optional string project = 7;
    public java.lang.String project;

    // optional string username = 8;
    public java.lang.String username;

    // optional string password = 9;
    public java.lang.String password;

    // optional string nickname = 10;
    public java.lang.String nickname;

    // optional string realname = 11;
    public java.lang.String realname;

    // optional int32 gender = 12;
    public int gender;

    // optional string birthday = 13;
    public java.lang.String birthday;

    // optional string email = 14;
    public java.lang.String email;

    // optional string cellphone = 15;
    public java.lang.String cellphone;

    // optional int32 timeZone = 16;
    public int timeZone;

    // optional string headImgURL = 17;
    public java.lang.String headImgURL;

    // optional string locale = 18;
    public java.lang.String locale;

    // optional string userResume = 19;
    public java.lang.String userResume;

    // optional int64 lastUpdateTime = 20;
    public long lastUpdateTime;

    // optional int64 lastLoginTime = 21;
    public long lastLoginTime;

    // map<string, string> userData = 22;
    public java.util.Map<java.lang.String, java.lang.String> userData;

    public PUserEx() {
      clear();
    }

    public PUserEx clear() {
      uuid = "";
      project = "";
      username = "";
      password = "";
      nickname = "";
      realname = "";
      gender = 0;
      birthday = "";
      email = "";
      cellphone = "";
      timeZone = 0;
      headImgURL = "";
      locale = "";
      userResume = "";
      lastUpdateTime = 0L;
      lastLoginTime = 0L;
      userData = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.uuid.equals("")) {
        output.writeString(6, this.uuid);
      }
      if (!this.project.equals("")) {
        output.writeString(7, this.project);
      }
      if (!this.username.equals("")) {
        output.writeString(8, this.username);
      }
      if (!this.password.equals("")) {
        output.writeString(9, this.password);
      }
      if (!this.nickname.equals("")) {
        output.writeString(10, this.nickname);
      }
      if (!this.realname.equals("")) {
        output.writeString(11, this.realname);
      }
      if (this.gender != 0) {
        output.writeInt32(12, this.gender);
      }
      if (!this.birthday.equals("")) {
        output.writeString(13, this.birthday);
      }
      if (!this.email.equals("")) {
        output.writeString(14, this.email);
      }
      if (!this.cellphone.equals("")) {
        output.writeString(15, this.cellphone);
      }
      if (this.timeZone != 0) {
        output.writeInt32(16, this.timeZone);
      }
      if (!this.headImgURL.equals("")) {
        output.writeString(17, this.headImgURL);
      }
      if (!this.locale.equals("")) {
        output.writeString(18, this.locale);
      }
      if (!this.userResume.equals("")) {
        output.writeString(19, this.userResume);
      }
      if (this.lastUpdateTime != 0L) {
        output.writeInt64(20, this.lastUpdateTime);
      }
      if (this.lastLoginTime != 0L) {
        output.writeInt64(21, this.lastLoginTime);
      }
      if (this.userData != null) {
        com.google.protobuf.nano.InternalNano.serializeMapField(
          output, this.userData, 22,
        com.google.protobuf.nano.InternalNano.TYPE_STRING,
        com.google.protobuf.nano.InternalNano.TYPE_STRING);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.uuid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.uuid);
      }
      if (!this.project.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.project);
      }
      if (!this.username.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.username);
      }
      if (!this.password.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(9, this.password);
      }
      if (!this.nickname.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(10, this.nickname);
      }
      if (!this.realname.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(11, this.realname);
      }
      if (this.gender != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(12, this.gender);
      }
      if (!this.birthday.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(13, this.birthday);
      }
      if (!this.email.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(14, this.email);
      }
      if (!this.cellphone.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(15, this.cellphone);
      }
      if (this.timeZone != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(16, this.timeZone);
      }
      if (!this.headImgURL.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(17, this.headImgURL);
      }
      if (!this.locale.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(18, this.locale);
      }
      if (!this.userResume.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(19, this.userResume);
      }
      if (this.lastUpdateTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(20, this.lastUpdateTime);
      }
      if (this.lastLoginTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(21, this.lastLoginTime);
      }
      if (this.userData != null) {
        size += com.google.protobuf.nano.InternalNano.computeMapFieldSize(
          this.userData, 22,
        com.google.protobuf.nano.InternalNano.TYPE_STRING,
        com.google.protobuf.nano.InternalNano.TYPE_STRING);
      }
      return size;
    }

    @Override
    public PUserEx mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      com.google.protobuf.nano.MapFactories.MapFactory mapFactory =
        com.google.protobuf.nano.MapFactories.getMapFactory();
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 50: {
            this.uuid = input.readString();
            break;
          }
          case 58: {
            this.project = input.readString();
            break;
          }
          case 66: {
            this.username = input.readString();
            break;
          }
          case 74: {
            this.password = input.readString();
            break;
          }
          case 82: {
            this.nickname = input.readString();
            break;
          }
          case 90: {
            this.realname = input.readString();
            break;
          }
          case 96: {
            this.gender = input.readInt32();
            break;
          }
          case 106: {
            this.birthday = input.readString();
            break;
          }
          case 114: {
            this.email = input.readString();
            break;
          }
          case 122: {
            this.cellphone = input.readString();
            break;
          }
          case 128: {
            this.timeZone = input.readInt32();
            break;
          }
          case 138: {
            this.headImgURL = input.readString();
            break;
          }
          case 146: {
            this.locale = input.readString();
            break;
          }
          case 154: {
            this.userResume = input.readString();
            break;
          }
          case 160: {
            this.lastUpdateTime = input.readInt64();
            break;
          }
          case 168: {
            this.lastLoginTime = input.readInt64();
            break;
          }
          case 178: {
            this.userData = com.google.protobuf.nano.InternalNano.mergeMapEntry(
              input, this.userData, mapFactory,
              com.google.protobuf.nano.InternalNano.TYPE_STRING,
              com.google.protobuf.nano.InternalNano.TYPE_STRING,
              null,
              10, 18);

            break;
          }
        }
      }
    }

    public static PUserEx parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PUserEx(), data);
    }

    public static PUserEx parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PUserEx().mergeFrom(input);
    }
  }

  public static final class PUserBase extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PUserBase[] _emptyArray;
    public static PUserBase[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PUserBase[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 Level = 2;
    public int level;

    // optional string UUID = 6;
    public java.lang.String uUID;

    // optional string UserName = 7;
    public java.lang.String userName;

    // optional string Nickname = 8;
    public java.lang.String nickname;

    // optional string HeadImgURL = 9;
    public java.lang.String headImgURL;

    public PUserBase() {
      clear();
    }

    public PUserBase clear() {
      level = 0;
      uUID = "";
      userName = "";
      nickname = "";
      headImgURL = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.level != 0) {
        output.writeInt32(2, this.level);
      }
      if (!this.uUID.equals("")) {
        output.writeString(6, this.uUID);
      }
      if (!this.userName.equals("")) {
        output.writeString(7, this.userName);
      }
      if (!this.nickname.equals("")) {
        output.writeString(8, this.nickname);
      }
      if (!this.headImgURL.equals("")) {
        output.writeString(9, this.headImgURL);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.level != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.level);
      }
      if (!this.uUID.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.uUID);
      }
      if (!this.userName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.userName);
      }
      if (!this.nickname.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.nickname);
      }
      if (!this.headImgURL.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(9, this.headImgURL);
      }
      return size;
    }

    @Override
    public PUserBase mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 16: {
            this.level = input.readInt32();
            break;
          }
          case 50: {
            this.uUID = input.readString();
            break;
          }
          case 58: {
            this.userName = input.readString();
            break;
          }
          case 66: {
            this.nickname = input.readString();
            break;
          }
          case 74: {
            this.headImgURL = input.readString();
            break;
          }
        }
      }
    }

    public static PUserBase parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PUserBase(), data);
    }

    public static PUserBase parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PUserBase().mergeFrom(input);
    }
  }

  public static final class PUserBaseList extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PUserBaseList[] _emptyArray;
    public static PUserBaseList[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PUserBaseList[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .common.PUserBase list = 1;
    public com.blemobi.sep.probuf.nano.AccountProtos.PUserBase[] list;

    public PUserBaseList() {
      clear();
    }

    public PUserBaseList clear() {
      list = com.blemobi.sep.probuf.nano.AccountProtos.PUserBase.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.AccountProtos.PUserBase element = this.list[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.AccountProtos.PUserBase element = this.list[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public PUserBaseList mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.list == null ? 0 : this.list.length;
            com.blemobi.sep.probuf.nano.AccountProtos.PUserBase[] newArray =
                new com.blemobi.sep.probuf.nano.AccountProtos.PUserBase[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.list, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.AccountProtos.PUserBase();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.AccountProtos.PUserBase();
            input.readMessage(newArray[i]);
            this.list = newArray;
            break;
          }
        }
      }
    }

    public static PUserBaseList parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PUserBaseList(), data);
    }

    public static PUserBaseList parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PUserBaseList().mergeFrom(input);
    }
  }

  public static final class PPhoneMap extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PPhoneMap[] _emptyArray;
    public static PPhoneMap[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PPhoneMap[0];
          }
        }
      }
      return _emptyArray;
    }

    // map<string, string> list = 1;
    public java.util.Map<java.lang.String, java.lang.String> list;

    public PPhoneMap() {
      clear();
    }

    public PPhoneMap clear() {
      list = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.list != null) {
        com.google.protobuf.nano.InternalNano.serializeMapField(
          output, this.list, 1,
        com.google.protobuf.nano.InternalNano.TYPE_STRING,
        com.google.protobuf.nano.InternalNano.TYPE_STRING);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.list != null) {
        size += com.google.protobuf.nano.InternalNano.computeMapFieldSize(
          this.list, 1,
        com.google.protobuf.nano.InternalNano.TYPE_STRING,
        com.google.protobuf.nano.InternalNano.TYPE_STRING);
      }
      return size;
    }

    @Override
    public PPhoneMap mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      com.google.protobuf.nano.MapFactories.MapFactory mapFactory =
        com.google.protobuf.nano.MapFactories.getMapFactory();
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.list = com.google.protobuf.nano.InternalNano.mergeMapEntry(
              input, this.list, mapFactory,
              com.google.protobuf.nano.InternalNano.TYPE_STRING,
              com.google.protobuf.nano.InternalNano.TYPE_STRING,
              null,
              10, 18);

            break;
          }
        }
      }
    }

    public static PPhoneMap parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PPhoneMap(), data);
    }

    public static PPhoneMap parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PPhoneMap().mergeFrom(input);
    }
  }

  public static final class PAccount extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PAccount[] _emptyArray;
    public static PAccount[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PAccount[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bool cellphone = 2;
    public boolean cellphone;

    // optional bool wechat = 3;
    public boolean wechat;

    // optional bool weibo = 4;
    public boolean weibo;

    // optional bool facebook = 5;
    public boolean facebook;

    // optional bool google = 6;
    public boolean google;

    public PAccount() {
      clear();
    }

    public PAccount clear() {
      cellphone = false;
      wechat = false;
      weibo = false;
      facebook = false;
      google = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.cellphone != false) {
        output.writeBool(2, this.cellphone);
      }
      if (this.wechat != false) {
        output.writeBool(3, this.wechat);
      }
      if (this.weibo != false) {
        output.writeBool(4, this.weibo);
      }
      if (this.facebook != false) {
        output.writeBool(5, this.facebook);
      }
      if (this.google != false) {
        output.writeBool(6, this.google);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.cellphone != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(2, this.cellphone);
      }
      if (this.wechat != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(3, this.wechat);
      }
      if (this.weibo != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(4, this.weibo);
      }
      if (this.facebook != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(5, this.facebook);
      }
      if (this.google != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(6, this.google);
      }
      return size;
    }

    @Override
    public PAccount mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 16: {
            this.cellphone = input.readBool();
            break;
          }
          case 24: {
            this.wechat = input.readBool();
            break;
          }
          case 32: {
            this.weibo = input.readBool();
            break;
          }
          case 40: {
            this.facebook = input.readBool();
            break;
          }
          case 48: {
            this.google = input.readBool();
            break;
          }
        }
      }
    }

    public static PAccount parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PAccount(), data);
    }

    public static PAccount parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PAccount().mergeFrom(input);
    }
  }

  public static final class PLevelInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PLevelInfo[] _emptyArray;
    public static PLevelInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PLevelInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 levelType = 1;
    public int levelType;

    // map<string, bool> mapRight = 2;
    public java.util.Map<java.lang.String, java.lang.Boolean> mapRight;

    public PLevelInfo() {
      clear();
    }

    public PLevelInfo clear() {
      levelType = 0;
      mapRight = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.levelType != 0) {
        output.writeInt32(1, this.levelType);
      }
      if (this.mapRight != null) {
        com.google.protobuf.nano.InternalNano.serializeMapField(
          output, this.mapRight, 2,
        com.google.protobuf.nano.InternalNano.TYPE_STRING,
        com.google.protobuf.nano.InternalNano.TYPE_BOOL);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.levelType != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.levelType);
      }
      if (this.mapRight != null) {
        size += com.google.protobuf.nano.InternalNano.computeMapFieldSize(
          this.mapRight, 2,
        com.google.protobuf.nano.InternalNano.TYPE_STRING,
        com.google.protobuf.nano.InternalNano.TYPE_BOOL);
      }
      return size;
    }

    @Override
    public PLevelInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      com.google.protobuf.nano.MapFactories.MapFactory mapFactory =
        com.google.protobuf.nano.MapFactories.getMapFactory();
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.levelType = input.readInt32();
            break;
          }
          case 18: {
            this.mapRight = com.google.protobuf.nano.InternalNano.mergeMapEntry(
              input, this.mapRight, mapFactory,
              com.google.protobuf.nano.InternalNano.TYPE_STRING,
              com.google.protobuf.nano.InternalNano.TYPE_BOOL,
              null,
              10, 16);

            break;
          }
        }
      }
    }

    public static PLevelInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PLevelInfo(), data);
    }

    public static PLevelInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PLevelInfo().mergeFrom(input);
    }
  }

  public static final class PLevelInfoEx extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PLevelInfoEx[] _emptyArray;
    public static PLevelInfoEx[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PLevelInfoEx[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string uuid = 1;
    public java.lang.String uuid;

    // optional .common.PLevelInfo levelInfo = 2;
    public com.blemobi.sep.probuf.nano.AccountProtos.PLevelInfo levelInfo;

    public PLevelInfoEx() {
      clear();
    }

    public PLevelInfoEx clear() {
      uuid = "";
      levelInfo = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.uuid.equals("")) {
        output.writeString(1, this.uuid);
      }
      if (this.levelInfo != null) {
        output.writeMessage(2, this.levelInfo);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.uuid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.uuid);
      }
      if (this.levelInfo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.levelInfo);
      }
      return size;
    }

    @Override
    public PLevelInfoEx mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.uuid = input.readString();
            break;
          }
          case 18: {
            if (this.levelInfo == null) {
              this.levelInfo = new com.blemobi.sep.probuf.nano.AccountProtos.PLevelInfo();
            }
            input.readMessage(this.levelInfo);
            break;
          }
        }
      }
    }

    public static PLevelInfoEx parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PLevelInfoEx(), data);
    }

    public static PLevelInfoEx parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PLevelInfoEx().mergeFrom(input);
    }
  }

  public static final class PLevelInfos extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PLevelInfos[] _emptyArray;
    public static PLevelInfos[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PLevelInfos[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .common.PLevelInfoEx list = 1;
    public com.blemobi.sep.probuf.nano.AccountProtos.PLevelInfoEx[] list;

    // repeated string failUuid = 2;
    public java.lang.String[] failUuid;

    public PLevelInfos() {
      clear();
    }

    public PLevelInfos clear() {
      list = com.blemobi.sep.probuf.nano.AccountProtos.PLevelInfoEx.emptyArray();
      failUuid = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.AccountProtos.PLevelInfoEx element = this.list[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      if (this.failUuid != null && this.failUuid.length > 0) {
        for (int i = 0; i < this.failUuid.length; i++) {
          java.lang.String element = this.failUuid[i];
          if (element != null) {
            output.writeString(2, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.AccountProtos.PLevelInfoEx element = this.list[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      if (this.failUuid != null && this.failUuid.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.failUuid.length; i++) {
          java.lang.String element = this.failUuid[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      return size;
    }

    @Override
    public PLevelInfos mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.list == null ? 0 : this.list.length;
            com.blemobi.sep.probuf.nano.AccountProtos.PLevelInfoEx[] newArray =
                new com.blemobi.sep.probuf.nano.AccountProtos.PLevelInfoEx[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.list, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.AccountProtos.PLevelInfoEx();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.AccountProtos.PLevelInfoEx();
            input.readMessage(newArray[i]);
            this.list = newArray;
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.failUuid == null ? 0 : this.failUuid.length;
            java.lang.String[] newArray = new java.lang.String[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.failUuid, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.failUuid = newArray;
            break;
          }
        }
      }
    }

    public static PLevelInfos parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PLevelInfos(), data);
    }

    public static PLevelInfos parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PLevelInfos().mergeFrom(input);
    }
  }

  public static final class PBlacklist extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PBlacklist[] _emptyArray;
    public static PBlacklist[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PBlacklist[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 id = 1;
    public long id;

    // optional string val = 2;
    public java.lang.String val;

    public PBlacklist() {
      clear();
    }

    public PBlacklist clear() {
      id = 0L;
      val = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.id != 0L) {
        output.writeInt64(1, this.id);
      }
      if (!this.val.equals("")) {
        output.writeString(2, this.val);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.id != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.id);
      }
      if (!this.val.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.val);
      }
      return size;
    }

    @Override
    public PBlacklist mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.id = input.readInt64();
            break;
          }
          case 18: {
            this.val = input.readString();
            break;
          }
        }
      }
    }

    public static PBlacklist parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PBlacklist(), data);
    }

    public static PBlacklist parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PBlacklist().mergeFrom(input);
    }
  }

  public static final class PBlacklistList extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PBlacklistList[] _emptyArray;
    public static PBlacklistList[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PBlacklistList[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .common.PBlacklist list = 1;
    public com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist[] list;

    public PBlacklistList() {
      clear();
    }

    public PBlacklistList clear() {
      list = com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist element = this.list[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist element = this.list[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public PBlacklistList mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.list == null ? 0 : this.list.length;
            com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist[] newArray =
                new com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.list, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist();
            input.readMessage(newArray[i]);
            this.list = newArray;
            break;
          }
        }
      }
    }

    public static PBlacklistList parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PBlacklistList(), data);
    }

    public static PBlacklistList parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PBlacklistList().mergeFrom(input);
    }
  }

  public static final class PBlacklistVal extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PBlacklistVal[] _emptyArray;
    public static PBlacklistVal[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PBlacklistVal[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated string list = 1;
    public java.lang.String[] list;

    public PBlacklistVal() {
      clear();
    }

    public PBlacklistVal clear() {
      list = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          java.lang.String element = this.list[i];
          if (element != null) {
            output.writeString(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.list != null && this.list.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.list.length; i++) {
          java.lang.String element = this.list[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      return size;
    }

    @Override
    public PBlacklistVal mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.list == null ? 0 : this.list.length;
            java.lang.String[] newArray = new java.lang.String[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.list, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.list = newArray;
            break;
          }
        }
      }
    }

    public static PBlacklistVal parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PBlacklistVal(), data);
    }

    public static PBlacklistVal parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PBlacklistVal().mergeFrom(input);
    }
  }

  public static final class PBlacklistID extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PBlacklistID[] _emptyArray;
    public static PBlacklistID[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PBlacklistID[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated int64 list = 1;
    public long[] list;

    public PBlacklistID() {
      clear();
    }

    public PBlacklistID clear() {
      list = com.google.protobuf.nano.WireFormatNano.EMPTY_LONG_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          output.writeInt64(1, this.list[i]);
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.list != null && this.list.length > 0) {
        int dataSize = 0;
        for (int i = 0; i < this.list.length; i++) {
          long element = this.list[i];
          dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt64SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * this.list.length;
      }
      return size;
    }

    @Override
    public PBlacklistID mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 8);
            int i = this.list == null ? 0 : this.list.length;
            long[] newArray = new long[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.list, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readInt64();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readInt64();
            this.list = newArray;
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            // First pass to compute array length.
            int arrayLength = 0;
            int startPos = input.getPosition();
            while (input.getBytesUntilLimit() > 0) {
              input.readInt64();
              arrayLength++;
            }
            input.rewindToPosition(startPos);
            int i = this.list == null ? 0 : this.list.length;
            long[] newArray = new long[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.list, 0, newArray, 0, i);
            }
            for (; i < newArray.length; i++) {
              newArray[i] = input.readInt64();
            }
            this.list = newArray;
            input.popLimit(limit);
            break;
          }
        }
      }
    }

    public static PBlacklistID parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PBlacklistID(), data);
    }

    public static PBlacklistID parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PBlacklistID().mergeFrom(input);
    }
  }

  public static final class PBlacklistRet extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PBlacklistRet[] _emptyArray;
    public static PBlacklistRet[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PBlacklistRet[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated int64 succList = 1;
    public long[] succList;

    // repeated int64 failList = 2;
    public long[] failList;

    public PBlacklistRet() {
      clear();
    }

    public PBlacklistRet clear() {
      succList = com.google.protobuf.nano.WireFormatNano.EMPTY_LONG_ARRAY;
      failList = com.google.protobuf.nano.WireFormatNano.EMPTY_LONG_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.succList != null && this.succList.length > 0) {
        for (int i = 0; i < this.succList.length; i++) {
          output.writeInt64(1, this.succList[i]);
        }
      }
      if (this.failList != null && this.failList.length > 0) {
        for (int i = 0; i < this.failList.length; i++) {
          output.writeInt64(2, this.failList[i]);
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.succList != null && this.succList.length > 0) {
        int dataSize = 0;
        for (int i = 0; i < this.succList.length; i++) {
          long element = this.succList[i];
          dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt64SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * this.succList.length;
      }
      if (this.failList != null && this.failList.length > 0) {
        int dataSize = 0;
        for (int i = 0; i < this.failList.length; i++) {
          long element = this.failList[i];
          dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt64SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * this.failList.length;
      }
      return size;
    }

    @Override
    public PBlacklistRet mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 8);
            int i = this.succList == null ? 0 : this.succList.length;
            long[] newArray = new long[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.succList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readInt64();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readInt64();
            this.succList = newArray;
            break;
          }
          case 10: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            // First pass to compute array length.
            int arrayLength = 0;
            int startPos = input.getPosition();
            while (input.getBytesUntilLimit() > 0) {
              input.readInt64();
              arrayLength++;
            }
            input.rewindToPosition(startPos);
            int i = this.succList == null ? 0 : this.succList.length;
            long[] newArray = new long[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.succList, 0, newArray, 0, i);
            }
            for (; i < newArray.length; i++) {
              newArray[i] = input.readInt64();
            }
            this.succList = newArray;
            input.popLimit(limit);
            break;
          }
          case 16: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 16);
            int i = this.failList == null ? 0 : this.failList.length;
            long[] newArray = new long[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.failList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readInt64();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readInt64();
            this.failList = newArray;
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            // First pass to compute array length.
            int arrayLength = 0;
            int startPos = input.getPosition();
            while (input.getBytesUntilLimit() > 0) {
              input.readInt64();
              arrayLength++;
            }
            input.rewindToPosition(startPos);
            int i = this.failList == null ? 0 : this.failList.length;
            long[] newArray = new long[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.failList, 0, newArray, 0, i);
            }
            for (; i < newArray.length; i++) {
              newArray[i] = input.readInt64();
            }
            this.failList = newArray;
            input.popLimit(limit);
            break;
          }
        }
      }
    }

    public static PBlacklistRet parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PBlacklistRet(), data);
    }

    public static PBlacklistRet parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PBlacklistRet().mergeFrom(input);
    }
  }

  public static final class PBlacklistExRet extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PBlacklistExRet[] _emptyArray;
    public static PBlacklistExRet[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PBlacklistExRet[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .common.PBlacklist succList = 1;
    public com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist[] succList;

    // repeated .common.PBlacklist existList = 2;
    public com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist[] existList;

    // repeated string failList = 3;
    public java.lang.String[] failList;

    public PBlacklistExRet() {
      clear();
    }

    public PBlacklistExRet clear() {
      succList = com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist.emptyArray();
      existList = com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist.emptyArray();
      failList = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.succList != null && this.succList.length > 0) {
        for (int i = 0; i < this.succList.length; i++) {
          com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist element = this.succList[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      if (this.existList != null && this.existList.length > 0) {
        for (int i = 0; i < this.existList.length; i++) {
          com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist element = this.existList[i];
          if (element != null) {
            output.writeMessage(2, element);
          }
        }
      }
      if (this.failList != null && this.failList.length > 0) {
        for (int i = 0; i < this.failList.length; i++) {
          java.lang.String element = this.failList[i];
          if (element != null) {
            output.writeString(3, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.succList != null && this.succList.length > 0) {
        for (int i = 0; i < this.succList.length; i++) {
          com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist element = this.succList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      if (this.existList != null && this.existList.length > 0) {
        for (int i = 0; i < this.existList.length; i++) {
          com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist element = this.existList[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(2, element);
          }
        }
      }
      if (this.failList != null && this.failList.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.failList.length; i++) {
          java.lang.String element = this.failList[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      return size;
    }

    @Override
    public PBlacklistExRet mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.succList == null ? 0 : this.succList.length;
            com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist[] newArray =
                new com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.succList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist();
            input.readMessage(newArray[i]);
            this.succList = newArray;
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.existList == null ? 0 : this.existList.length;
            com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist[] newArray =
                new com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.existList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.AccountProtos.PBlacklist();
            input.readMessage(newArray[i]);
            this.existList = newArray;
            break;
          }
          case 26: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.failList == null ? 0 : this.failList.length;
            java.lang.String[] newArray = new java.lang.String[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.failList, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.failList = newArray;
            break;
          }
        }
      }
    }

    public static PBlacklistExRet parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PBlacklistExRet(), data);
    }

    public static PBlacklistExRet parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PBlacklistExRet().mergeFrom(input);
    }
  }

  public static final class PBlacklistCount extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PBlacklistCount[] _emptyArray;
    public static PBlacklistCount[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PBlacklistCount[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 count = 1;
    public long count;

    public PBlacklistCount() {
      clear();
    }

    public PBlacklistCount clear() {
      count = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.count != 0L) {
        output.writeInt64(1, this.count);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.count != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.count);
      }
      return size;
    }

    @Override
    public PBlacklistCount mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.count = input.readInt64();
            break;
          }
        }
      }
    }

    public static PBlacklistCount parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PBlacklistCount(), data);
    }

    public static PBlacklistCount parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PBlacklistCount().mergeFrom(input);
    }
  }
}
