// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.blemobi.sep.probuf.nano;

@SuppressWarnings("hiding")
public interface LoginProtos {

  public static final class PLogin extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PLogin[] _emptyArray;
    public static PLogin[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PLogin[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bool newUser = 5;
    public boolean newUser;

    // optional string uuid = 6;
    public java.lang.String uuid;

    // optional string token = 7;
    public java.lang.String token;

    // optional string nickname = 8;
    public java.lang.String nickname;

    // optional string imgURL = 9;
    public java.lang.String imgURL;

    // optional int64 chatid = 10;
    public long chatid;

    // repeated int32 loginTypes = 11;
    public int[] loginTypes;

    // optional .common.PLevelInfo levelInfo = 12;
    public com.blemobi.sep.probuf.nano.AccountProtos.PLevelInfo levelInfo;

    public PLogin() {
      clear();
    }

    public PLogin clear() {
      newUser = false;
      uuid = "";
      token = "";
      nickname = "";
      imgURL = "";
      chatid = 0L;
      loginTypes = com.google.protobuf.nano.WireFormatNano.EMPTY_INT_ARRAY;
      levelInfo = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.newUser != false) {
        output.writeBool(5, this.newUser);
      }
      if (!this.uuid.equals("")) {
        output.writeString(6, this.uuid);
      }
      if (!this.token.equals("")) {
        output.writeString(7, this.token);
      }
      if (!this.nickname.equals("")) {
        output.writeString(8, this.nickname);
      }
      if (!this.imgURL.equals("")) {
        output.writeString(9, this.imgURL);
      }
      if (this.chatid != 0L) {
        output.writeInt64(10, this.chatid);
      }
      if (this.loginTypes != null && this.loginTypes.length > 0) {
        for (int i = 0; i < this.loginTypes.length; i++) {
          output.writeInt32(11, this.loginTypes[i]);
        }
      }
      if (this.levelInfo != null) {
        output.writeMessage(12, this.levelInfo);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.newUser != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(5, this.newUser);
      }
      if (!this.uuid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.uuid);
      }
      if (!this.token.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.token);
      }
      if (!this.nickname.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.nickname);
      }
      if (!this.imgURL.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(9, this.imgURL);
      }
      if (this.chatid != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(10, this.chatid);
      }
      if (this.loginTypes != null && this.loginTypes.length > 0) {
        int dataSize = 0;
        for (int i = 0; i < this.loginTypes.length; i++) {
          int element = this.loginTypes[i];
          dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * this.loginTypes.length;
      }
      if (this.levelInfo != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(12, this.levelInfo);
      }
      return size;
    }

    @Override
    public PLogin mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 40: {
            this.newUser = input.readBool();
            break;
          }
          case 50: {
            this.uuid = input.readString();
            break;
          }
          case 58: {
            this.token = input.readString();
            break;
          }
          case 66: {
            this.nickname = input.readString();
            break;
          }
          case 74: {
            this.imgURL = input.readString();
            break;
          }
          case 80: {
            this.chatid = input.readInt64();
            break;
          }
          case 88: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 88);
            int i = this.loginTypes == null ? 0 : this.loginTypes.length;
            int[] newArray = new int[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.loginTypes, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readInt32();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readInt32();
            this.loginTypes = newArray;
            break;
          }
          case 90: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            // First pass to compute array length.
            int arrayLength = 0;
            int startPos = input.getPosition();
            while (input.getBytesUntilLimit() > 0) {
              input.readInt32();
              arrayLength++;
            }
            input.rewindToPosition(startPos);
            int i = this.loginTypes == null ? 0 : this.loginTypes.length;
            int[] newArray = new int[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.loginTypes, 0, newArray, 0, i);
            }
            for (; i < newArray.length; i++) {
              newArray[i] = input.readInt32();
            }
            this.loginTypes = newArray;
            input.popLimit(limit);
            break;
          }
          case 98: {
            if (this.levelInfo == null) {
              this.levelInfo = new com.blemobi.sep.probuf.nano.AccountProtos.PLevelInfo();
            }
            input.readMessage(this.levelInfo);
            break;
          }
        }
      }
    }

    public static PLogin parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PLogin(), data);
    }

    public static PLogin parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PLogin().mergeFrom(input);
    }
  }

  public static final class PLoginType extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PLoginType[] _emptyArray;
    public static PLoginType[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PLoginType[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated int32 types = 2;
    public int[] types;

    public PLoginType() {
      clear();
    }

    public PLoginType clear() {
      types = com.google.protobuf.nano.WireFormatNano.EMPTY_INT_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.types != null && this.types.length > 0) {
        for (int i = 0; i < this.types.length; i++) {
          output.writeInt32(2, this.types[i]);
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.types != null && this.types.length > 0) {
        int dataSize = 0;
        for (int i = 0; i < this.types.length; i++) {
          int element = this.types[i];
          dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeInt32SizeNoTag(element);
        }
        size += dataSize;
        size += 1 * this.types.length;
      }
      return size;
    }

    @Override
    public PLoginType mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 16: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 16);
            int i = this.types == null ? 0 : this.types.length;
            int[] newArray = new int[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.types, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readInt32();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readInt32();
            this.types = newArray;
            break;
          }
          case 18: {
            int length = input.readRawVarint32();
            int limit = input.pushLimit(length);
            // First pass to compute array length.
            int arrayLength = 0;
            int startPos = input.getPosition();
            while (input.getBytesUntilLimit() > 0) {
              input.readInt32();
              arrayLength++;
            }
            input.rewindToPosition(startPos);
            int i = this.types == null ? 0 : this.types.length;
            int[] newArray = new int[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.types, 0, newArray, 0, i);
            }
            for (; i < newArray.length; i++) {
              newArray[i] = input.readInt32();
            }
            this.types = newArray;
            input.popLimit(limit);
            break;
          }
        }
      }
    }

    public static PLoginType parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PLoginType(), data);
    }

    public static PLoginType parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PLoginType().mergeFrom(input);
    }
  }

  public static final class PRUsername extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PRUsername[] _emptyArray;
    public static PRUsername[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PRUsername[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated string names = 2;
    public java.lang.String[] names;

    public PRUsername() {
      clear();
    }

    public PRUsername clear() {
      names = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.names != null && this.names.length > 0) {
        for (int i = 0; i < this.names.length; i++) {
          java.lang.String element = this.names[i];
          if (element != null) {
            output.writeString(2, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.names != null && this.names.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.names.length; i++) {
          java.lang.String element = this.names[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      return size;
    }

    @Override
    public PRUsername mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 18: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 18);
            int i = this.names == null ? 0 : this.names.length;
            java.lang.String[] newArray = new java.lang.String[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.names, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.names = newArray;
            break;
          }
        }
      }
    }

    public static PRUsername parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PRUsername(), data);
    }

    public static PRUsername parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PRUsername().mergeFrom(input);
    }
  }

  public static final class PToken extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PToken[] _emptyArray;
    public static PToken[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PToken[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string SaltMD5 = 2;
    public java.lang.String saltMD5;

    // optional int64 CreateTime = 3;
    public long createTime;

    public PToken() {
      clear();
    }

    public PToken clear() {
      saltMD5 = "";
      createTime = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.saltMD5.equals("")) {
        output.writeString(2, this.saltMD5);
      }
      if (this.createTime != 0L) {
        output.writeInt64(3, this.createTime);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.saltMD5.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.saltMD5);
      }
      if (this.createTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, this.createTime);
      }
      return size;
    }

    @Override
    public PToken mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 18: {
            this.saltMD5 = input.readString();
            break;
          }
          case 24: {
            this.createTime = input.readInt64();
            break;
          }
        }
      }
    }

    public static PToken parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PToken(), data);
    }

    public static PToken parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PToken().mergeFrom(input);
    }
  }
}
