// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.blemobi.sep.probuf.nano;

@SuppressWarnings("hiding")
public interface MsgResultProtos {

  public static final class PQuerySingleMessage extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PQuerySingleMessage[] _emptyArray;
    public static PQuerySingleMessage[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PQuerySingleMessage[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 errorCode = 1;
    public int errorCode;

    // optional string errorMsg = 2;
    public java.lang.String errorMsg;

    // optional string contentType = 3;
    public java.lang.String contentType;

    // optional bytes data = 4;
    public byte[] data;

    public PQuerySingleMessage() {
      clear();
    }

    public PQuerySingleMessage clear() {
      errorCode = 0;
      errorMsg = "";
      contentType = "";
      data = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.errorCode != 0) {
        output.writeInt32(1, this.errorCode);
      }
      if (!this.errorMsg.equals("")) {
        output.writeString(2, this.errorMsg);
      }
      if (!this.contentType.equals("")) {
        output.writeString(3, this.contentType);
      }
      if (!java.util.Arrays.equals(this.data, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(4, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.errorCode != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.errorCode);
      }
      if (!this.errorMsg.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.errorMsg);
      }
      if (!this.contentType.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.contentType);
      }
      if (!java.util.Arrays.equals(this.data, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(4, this.data);
      }
      return size;
    }

    @Override
    public PQuerySingleMessage mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.errorCode = input.readInt32();
            break;
          }
          case 18: {
            this.errorMsg = input.readString();
            break;
          }
          case 26: {
            this.contentType = input.readString();
            break;
          }
          case 34: {
            this.data = input.readBytes();
            break;
          }
        }
      }
    }

    public static PQuerySingleMessage parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PQuerySingleMessage(), data);
    }

    public static PQuerySingleMessage parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PQuerySingleMessage().mergeFrom(input);
    }
  }

  public static final class PQueryMoreMessage extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PQueryMoreMessage[] _emptyArray;
    public static PQueryMoreMessage[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PQueryMoreMessage[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 errorCode = 1;
    public int errorCode;

    // optional string errorMsg = 2;
    public java.lang.String errorMsg;

    // repeated .common.PMessageData data = 3;
    public com.blemobi.sep.probuf.nano.MsgResultProtos.PMessageData[] data;

    public PQueryMoreMessage() {
      clear();
    }

    public PQueryMoreMessage clear() {
      errorCode = 0;
      errorMsg = "";
      data = com.blemobi.sep.probuf.nano.MsgResultProtos.PMessageData.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.errorCode != 0) {
        output.writeInt32(1, this.errorCode);
      }
      if (!this.errorMsg.equals("")) {
        output.writeString(2, this.errorMsg);
      }
      if (this.data != null && this.data.length > 0) {
        for (int i = 0; i < this.data.length; i++) {
          com.blemobi.sep.probuf.nano.MsgResultProtos.PMessageData element = this.data[i];
          if (element != null) {
            output.writeMessage(3, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.errorCode != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.errorCode);
      }
      if (!this.errorMsg.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.errorMsg);
      }
      if (this.data != null && this.data.length > 0) {
        for (int i = 0; i < this.data.length; i++) {
          com.blemobi.sep.probuf.nano.MsgResultProtos.PMessageData element = this.data[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(3, element);
          }
        }
      }
      return size;
    }

    @Override
    public PQueryMoreMessage mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.errorCode = input.readInt32();
            break;
          }
          case 18: {
            this.errorMsg = input.readString();
            break;
          }
          case 26: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.data == null ? 0 : this.data.length;
            com.blemobi.sep.probuf.nano.MsgResultProtos.PMessageData[] newArray =
                new com.blemobi.sep.probuf.nano.MsgResultProtos.PMessageData[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.data, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.MsgResultProtos.PMessageData();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.MsgResultProtos.PMessageData();
            input.readMessage(newArray[i]);
            this.data = newArray;
            break;
          }
        }
      }
    }

    public static PQueryMoreMessage parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PQueryMoreMessage(), data);
    }

    public static PQueryMoreMessage parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PQueryMoreMessage().mergeFrom(input);
    }
  }

  public static final class PMessageData extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PMessageData[] _emptyArray;
    public static PMessageData[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PMessageData[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string openId = 1;
    public java.lang.String openId;

    // optional string messageId = 2;
    public java.lang.String messageId;

    // optional string createdAt = 3;
    public java.lang.String createdAt;

    // optional string conversationId = 4;
    public java.lang.String conversationId;

    // optional string contentType = 5;
    public java.lang.String contentType;

    // optional bytes data = 6;
    public byte[] data;

    public PMessageData() {
      clear();
    }

    public PMessageData clear() {
      openId = "";
      messageId = "";
      createdAt = "";
      conversationId = "";
      contentType = "";
      data = com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.openId.equals("")) {
        output.writeString(1, this.openId);
      }
      if (!this.messageId.equals("")) {
        output.writeString(2, this.messageId);
      }
      if (!this.createdAt.equals("")) {
        output.writeString(3, this.createdAt);
      }
      if (!this.conversationId.equals("")) {
        output.writeString(4, this.conversationId);
      }
      if (!this.contentType.equals("")) {
        output.writeString(5, this.contentType);
      }
      if (!java.util.Arrays.equals(this.data, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        output.writeBytes(6, this.data);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.openId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.openId);
      }
      if (!this.messageId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.messageId);
      }
      if (!this.createdAt.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.createdAt);
      }
      if (!this.conversationId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.conversationId);
      }
      if (!this.contentType.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.contentType);
      }
      if (!java.util.Arrays.equals(this.data, com.google.protobuf.nano.WireFormatNano.EMPTY_BYTES)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBytesSize(6, this.data);
      }
      return size;
    }

    @Override
    public PMessageData mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.openId = input.readString();
            break;
          }
          case 18: {
            this.messageId = input.readString();
            break;
          }
          case 26: {
            this.createdAt = input.readString();
            break;
          }
          case 34: {
            this.conversationId = input.readString();
            break;
          }
          case 42: {
            this.contentType = input.readString();
            break;
          }
          case 50: {
            this.data = input.readBytes();
            break;
          }
        }
      }
    }

    public static PMessageData parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PMessageData(), data);
    }

    public static PMessageData parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PMessageData().mergeFrom(input);
    }
  }

  public static final class PTextMsg extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PTextMsg[] _emptyArray;
    public static PTextMsg[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PTextMsg[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string text = 1;
    public java.lang.String text;

    public PTextMsg() {
      clear();
    }

    public PTextMsg clear() {
      text = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.text.equals("")) {
        output.writeString(1, this.text);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.text.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.text);
      }
      return size;
    }

    @Override
    public PTextMsg mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.text = input.readString();
            break;
          }
        }
      }
    }

    public static PTextMsg parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PTextMsg(), data);
    }

    public static PTextMsg parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PTextMsg().mergeFrom(input);
    }
  }

  public static final class PImageMsg extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PImageMsg[] _emptyArray;
    public static PImageMsg[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PImageMsg[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string mediaId = 1;
    public java.lang.String mediaId;

    // optional int32 mediaSize = 2;
    public int mediaSize;

    // optional string mediaUrl = 3;
    public java.lang.String mediaUrl;

    public PImageMsg() {
      clear();
    }

    public PImageMsg clear() {
      mediaId = "";
      mediaSize = 0;
      mediaUrl = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.mediaId.equals("")) {
        output.writeString(1, this.mediaId);
      }
      if (this.mediaSize != 0) {
        output.writeInt32(2, this.mediaSize);
      }
      if (!this.mediaUrl.equals("")) {
        output.writeString(3, this.mediaUrl);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.mediaId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.mediaId);
      }
      if (this.mediaSize != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.mediaSize);
      }
      if (!this.mediaUrl.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.mediaUrl);
      }
      return size;
    }

    @Override
    public PImageMsg mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.mediaId = input.readString();
            break;
          }
          case 16: {
            this.mediaSize = input.readInt32();
            break;
          }
          case 26: {
            this.mediaUrl = input.readString();
            break;
          }
        }
      }
    }

    public static PImageMsg parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PImageMsg(), data);
    }

    public static PImageMsg parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PImageMsg().mergeFrom(input);
    }
  }

  public static final class PAudioMsg extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PAudioMsg[] _emptyArray;
    public static PAudioMsg[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PAudioMsg[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string mediaId = 1;
    public java.lang.String mediaId;

    // optional int32 duration = 2;
    public int duration;

    // optional int32 audioVolumns = 3;
    public int audioVolumns;

    // optional string mediaUrl = 4;
    public java.lang.String mediaUrl;

    public PAudioMsg() {
      clear();
    }

    public PAudioMsg clear() {
      mediaId = "";
      duration = 0;
      audioVolumns = 0;
      mediaUrl = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.mediaId.equals("")) {
        output.writeString(1, this.mediaId);
      }
      if (this.duration != 0) {
        output.writeInt32(2, this.duration);
      }
      if (this.audioVolumns != 0) {
        output.writeInt32(3, this.audioVolumns);
      }
      if (!this.mediaUrl.equals("")) {
        output.writeString(4, this.mediaUrl);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.mediaId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.mediaId);
      }
      if (this.duration != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.duration);
      }
      if (this.audioVolumns != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.audioVolumns);
      }
      if (!this.mediaUrl.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.mediaUrl);
      }
      return size;
    }

    @Override
    public PAudioMsg mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.mediaId = input.readString();
            break;
          }
          case 16: {
            this.duration = input.readInt32();
            break;
          }
          case 24: {
            this.audioVolumns = input.readInt32();
            break;
          }
          case 34: {
            this.mediaUrl = input.readString();
            break;
          }
        }
      }
    }

    public static PAudioMsg parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PAudioMsg(), data);
    }

    public static PAudioMsg parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PAudioMsg().mergeFrom(input);
    }
  }

  public static final class PAudioImageMsg extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PAudioImageMsg[] _emptyArray;
    public static PAudioImageMsg[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PAudioImageMsg[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string mediaId = 1;
    public java.lang.String mediaId;

    // optional int32 mediaSize = 2;
    public int mediaSize;

    // optional int32 duration = 3;
    public int duration;

    // optional int32 audioVolumns = 4;
    public int audioVolumns;

    // optional string mediaUrl = 5;
    public java.lang.String mediaUrl;

    public PAudioImageMsg() {
      clear();
    }

    public PAudioImageMsg clear() {
      mediaId = "";
      mediaSize = 0;
      duration = 0;
      audioVolumns = 0;
      mediaUrl = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.mediaId.equals("")) {
        output.writeString(1, this.mediaId);
      }
      if (this.mediaSize != 0) {
        output.writeInt32(2, this.mediaSize);
      }
      if (this.duration != 0) {
        output.writeInt32(3, this.duration);
      }
      if (this.audioVolumns != 0) {
        output.writeInt32(4, this.audioVolumns);
      }
      if (!this.mediaUrl.equals("")) {
        output.writeString(5, this.mediaUrl);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.mediaId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.mediaId);
      }
      if (this.mediaSize != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.mediaSize);
      }
      if (this.duration != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.duration);
      }
      if (this.audioVolumns != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.audioVolumns);
      }
      if (!this.mediaUrl.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.mediaUrl);
      }
      return size;
    }

    @Override
    public PAudioImageMsg mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.mediaId = input.readString();
            break;
          }
          case 16: {
            this.mediaSize = input.readInt32();
            break;
          }
          case 24: {
            this.duration = input.readInt32();
            break;
          }
          case 32: {
            this.audioVolumns = input.readInt32();
            break;
          }
          case 42: {
            this.mediaUrl = input.readString();
            break;
          }
        }
      }
    }

    public static PAudioImageMsg parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PAudioImageMsg(), data);
    }

    public static PAudioImageMsg parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PAudioImageMsg().mergeFrom(input);
    }
  }

  public static final class PFileMsg extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PFileMsg[] _emptyArray;
    public static PFileMsg[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PFileMsg[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string fileName = 1;
    public java.lang.String fileName;

    // optional string fileType = 2;
    public java.lang.String fileType;

    // optional string mediaId = 3;
    public java.lang.String mediaId;

    // optional int32 fileSize = 4;
    public int fileSize;

    // optional string mediaUrl = 5;
    public java.lang.String mediaUrl;

    public PFileMsg() {
      clear();
    }

    public PFileMsg clear() {
      fileName = "";
      fileType = "";
      mediaId = "";
      fileSize = 0;
      mediaUrl = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.fileName.equals("")) {
        output.writeString(1, this.fileName);
      }
      if (!this.fileType.equals("")) {
        output.writeString(2, this.fileType);
      }
      if (!this.mediaId.equals("")) {
        output.writeString(3, this.mediaId);
      }
      if (this.fileSize != 0) {
        output.writeInt32(4, this.fileSize);
      }
      if (!this.mediaUrl.equals("")) {
        output.writeString(5, this.mediaUrl);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.fileName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.fileName);
      }
      if (!this.fileType.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.fileType);
      }
      if (!this.mediaId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.mediaId);
      }
      if (this.fileSize != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.fileSize);
      }
      if (!this.mediaUrl.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.mediaUrl);
      }
      return size;
    }

    @Override
    public PFileMsg mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.fileName = input.readString();
            break;
          }
          case 18: {
            this.fileType = input.readString();
            break;
          }
          case 26: {
            this.mediaId = input.readString();
            break;
          }
          case 32: {
            this.fileSize = input.readInt32();
            break;
          }
          case 42: {
            this.mediaUrl = input.readString();
            break;
          }
        }
      }
    }

    public static PFileMsg parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PFileMsg(), data);
    }

    public static PFileMsg parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PFileMsg().mergeFrom(input);
    }
  }
}
