// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.blemobi.sep.probuf.nano;

@SuppressWarnings("hiding")
public interface NewsProtos {

  public static final class PPostInfoList extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PPostInfoList[] _emptyArray;
    public static PPostInfoList[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PPostInfoList[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .common.PPostInfo list = 1;
    public com.blemobi.sep.probuf.nano.NewsProtos.PPostInfo[] list;

    public PPostInfoList() {
      clear();
    }

    public PPostInfoList clear() {
      list = com.blemobi.sep.probuf.nano.NewsProtos.PPostInfo.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.NewsProtos.PPostInfo element = this.list[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.NewsProtos.PPostInfo element = this.list[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public PPostInfoList mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.list == null ? 0 : this.list.length;
            com.blemobi.sep.probuf.nano.NewsProtos.PPostInfo[] newArray =
                new com.blemobi.sep.probuf.nano.NewsProtos.PPostInfo[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.list, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.NewsProtos.PPostInfo();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.NewsProtos.PPostInfo();
            input.readMessage(newArray[i]);
            this.list = newArray;
            break;
          }
        }
      }
    }

    public static PPostInfoList parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PPostInfoList(), data);
    }

    public static PPostInfoList parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PPostInfoList().mergeFrom(input);
    }
  }

  public static final class PPostInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PPostInfo[] _emptyArray;
    public static PPostInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PPostInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 id = 1;
    public long id;

    // optional string uuid = 2;
    public java.lang.String uuid;

    // optional string userName = 3;
    public java.lang.String userName;

    // optional string userHead = 4;
    public java.lang.String userHead;

    // optional string content = 5;
    public java.lang.String content;

    // optional string srcType = 6;
    public java.lang.String srcType;

    // repeated .common.PImage images = 7;
    public com.blemobi.sep.probuf.nano.NewsProtos.PImage[] images;

    // optional .common.PVideo video = 8;
    public com.blemobi.sep.probuf.nano.NewsProtos.PVideo video;

    // optional .common.PAudio audio = 9;
    public com.blemobi.sep.probuf.nano.NewsProtos.PAudio audio;

    // optional int64 pubishTime = 11;
    public long pubishTime;

    // optional string position = 12;
    public java.lang.String position;

    // optional bool self = 14;
    public boolean self;

    // optional bool collected = 15;
    public boolean collected;

    // optional int64 commentCnt = 16;
    public long commentCnt;

    // optional int64 collectCnt = 17;
    public long collectCnt;

    // optional int64 voteCnt = 18;
    public long voteCnt;

    // optional bool vote = 19;
    public boolean vote;

    // optional .common.PAtUserList atusers = 20;
    public com.blemobi.sep.probuf.nano.NewsProtos.PAtUserList atusers;

    // optional bool IsDelete = 21;
    public boolean isDelete;

    // optional bool IsHide = 22;
    public boolean isHide;

    // optional .common.PRedPacketInfo RedPacket = 23;
    public com.blemobi.sep.probuf.nano.WalletProtos.PRedPacketInfo redPacket;

    public PPostInfo() {
      clear();
    }

    public PPostInfo clear() {
      id = 0L;
      uuid = "";
      userName = "";
      userHead = "";
      content = "";
      srcType = "";
      images = com.blemobi.sep.probuf.nano.NewsProtos.PImage.emptyArray();
      video = null;
      audio = null;
      pubishTime = 0L;
      position = "";
      self = false;
      collected = false;
      commentCnt = 0L;
      collectCnt = 0L;
      voteCnt = 0L;
      vote = false;
      atusers = null;
      isDelete = false;
      isHide = false;
      redPacket = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.id != 0L) {
        output.writeInt64(1, this.id);
      }
      if (!this.uuid.equals("")) {
        output.writeString(2, this.uuid);
      }
      if (!this.userName.equals("")) {
        output.writeString(3, this.userName);
      }
      if (!this.userHead.equals("")) {
        output.writeString(4, this.userHead);
      }
      if (!this.content.equals("")) {
        output.writeString(5, this.content);
      }
      if (!this.srcType.equals("")) {
        output.writeString(6, this.srcType);
      }
      if (this.images != null && this.images.length > 0) {
        for (int i = 0; i < this.images.length; i++) {
          com.blemobi.sep.probuf.nano.NewsProtos.PImage element = this.images[i];
          if (element != null) {
            output.writeMessage(7, element);
          }
        }
      }
      if (this.video != null) {
        output.writeMessage(8, this.video);
      }
      if (this.audio != null) {
        output.writeMessage(9, this.audio);
      }
      if (this.pubishTime != 0L) {
        output.writeInt64(11, this.pubishTime);
      }
      if (!this.position.equals("")) {
        output.writeString(12, this.position);
      }
      if (this.self != false) {
        output.writeBool(14, this.self);
      }
      if (this.collected != false) {
        output.writeBool(15, this.collected);
      }
      if (this.commentCnt != 0L) {
        output.writeInt64(16, this.commentCnt);
      }
      if (this.collectCnt != 0L) {
        output.writeInt64(17, this.collectCnt);
      }
      if (this.voteCnt != 0L) {
        output.writeInt64(18, this.voteCnt);
      }
      if (this.vote != false) {
        output.writeBool(19, this.vote);
      }
      if (this.atusers != null) {
        output.writeMessage(20, this.atusers);
      }
      if (this.isDelete != false) {
        output.writeBool(21, this.isDelete);
      }
      if (this.isHide != false) {
        output.writeBool(22, this.isHide);
      }
      if (this.redPacket != null) {
        output.writeMessage(23, this.redPacket);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.id != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.id);
      }
      if (!this.uuid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.uuid);
      }
      if (!this.userName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.userName);
      }
      if (!this.userHead.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.userHead);
      }
      if (!this.content.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.content);
      }
      if (!this.srcType.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.srcType);
      }
      if (this.images != null && this.images.length > 0) {
        for (int i = 0; i < this.images.length; i++) {
          com.blemobi.sep.probuf.nano.NewsProtos.PImage element = this.images[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(7, element);
          }
        }
      }
      if (this.video != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(8, this.video);
      }
      if (this.audio != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(9, this.audio);
      }
      if (this.pubishTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(11, this.pubishTime);
      }
      if (!this.position.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(12, this.position);
      }
      if (this.self != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(14, this.self);
      }
      if (this.collected != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(15, this.collected);
      }
      if (this.commentCnt != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(16, this.commentCnt);
      }
      if (this.collectCnt != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(17, this.collectCnt);
      }
      if (this.voteCnt != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(18, this.voteCnt);
      }
      if (this.vote != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(19, this.vote);
      }
      if (this.atusers != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(20, this.atusers);
      }
      if (this.isDelete != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(21, this.isDelete);
      }
      if (this.isHide != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(22, this.isHide);
      }
      if (this.redPacket != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(23, this.redPacket);
      }
      return size;
    }

    @Override
    public PPostInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.id = input.readInt64();
            break;
          }
          case 18: {
            this.uuid = input.readString();
            break;
          }
          case 26: {
            this.userName = input.readString();
            break;
          }
          case 34: {
            this.userHead = input.readString();
            break;
          }
          case 42: {
            this.content = input.readString();
            break;
          }
          case 50: {
            this.srcType = input.readString();
            break;
          }
          case 58: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 58);
            int i = this.images == null ? 0 : this.images.length;
            com.blemobi.sep.probuf.nano.NewsProtos.PImage[] newArray =
                new com.blemobi.sep.probuf.nano.NewsProtos.PImage[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.images, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.NewsProtos.PImage();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.NewsProtos.PImage();
            input.readMessage(newArray[i]);
            this.images = newArray;
            break;
          }
          case 66: {
            if (this.video == null) {
              this.video = new com.blemobi.sep.probuf.nano.NewsProtos.PVideo();
            }
            input.readMessage(this.video);
            break;
          }
          case 74: {
            if (this.audio == null) {
              this.audio = new com.blemobi.sep.probuf.nano.NewsProtos.PAudio();
            }
            input.readMessage(this.audio);
            break;
          }
          case 88: {
            this.pubishTime = input.readInt64();
            break;
          }
          case 98: {
            this.position = input.readString();
            break;
          }
          case 112: {
            this.self = input.readBool();
            break;
          }
          case 120: {
            this.collected = input.readBool();
            break;
          }
          case 128: {
            this.commentCnt = input.readInt64();
            break;
          }
          case 136: {
            this.collectCnt = input.readInt64();
            break;
          }
          case 144: {
            this.voteCnt = input.readInt64();
            break;
          }
          case 152: {
            this.vote = input.readBool();
            break;
          }
          case 162: {
            if (this.atusers == null) {
              this.atusers = new com.blemobi.sep.probuf.nano.NewsProtos.PAtUserList();
            }
            input.readMessage(this.atusers);
            break;
          }
          case 168: {
            this.isDelete = input.readBool();
            break;
          }
          case 176: {
            this.isHide = input.readBool();
            break;
          }
          case 186: {
            if (this.redPacket == null) {
              this.redPacket = new com.blemobi.sep.probuf.nano.WalletProtos.PRedPacketInfo();
            }
            input.readMessage(this.redPacket);
            break;
          }
        }
      }
    }

    public static PPostInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PPostInfo(), data);
    }

    public static PPostInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PPostInfo().mergeFrom(input);
    }
  }

  public static final class PAtUserList extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PAtUserList[] _emptyArray;
    public static PAtUserList[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PAtUserList[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .common.PAtUser list = 1;
    public com.blemobi.sep.probuf.nano.NewsProtos.PAtUser[] list;

    public PAtUserList() {
      clear();
    }

    public PAtUserList clear() {
      list = com.blemobi.sep.probuf.nano.NewsProtos.PAtUser.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.NewsProtos.PAtUser element = this.list[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.NewsProtos.PAtUser element = this.list[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public PAtUserList mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.list == null ? 0 : this.list.length;
            com.blemobi.sep.probuf.nano.NewsProtos.PAtUser[] newArray =
                new com.blemobi.sep.probuf.nano.NewsProtos.PAtUser[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.list, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.NewsProtos.PAtUser();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.NewsProtos.PAtUser();
            input.readMessage(newArray[i]);
            this.list = newArray;
            break;
          }
        }
      }
    }

    public static PAtUserList parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PAtUserList(), data);
    }

    public static PAtUserList parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PAtUserList().mergeFrom(input);
    }
  }

  public static final class PAtUser extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PAtUser[] _emptyArray;
    public static PAtUser[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PAtUser[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string uuid = 1;
    public java.lang.String uuid;

    // optional string nickName = 2;
    public java.lang.String nickName;

    public PAtUser() {
      clear();
    }

    public PAtUser clear() {
      uuid = "";
      nickName = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.uuid.equals("")) {
        output.writeString(1, this.uuid);
      }
      if (!this.nickName.equals("")) {
        output.writeString(2, this.nickName);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.uuid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.uuid);
      }
      if (!this.nickName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.nickName);
      }
      return size;
    }

    @Override
    public PAtUser mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.uuid = input.readString();
            break;
          }
          case 18: {
            this.nickName = input.readString();
            break;
          }
        }
      }
    }

    public static PAtUser parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PAtUser(), data);
    }

    public static PAtUser parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PAtUser().mergeFrom(input);
    }
  }

  public static final class PImage extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PImage[] _emptyArray;
    public static PImage[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PImage[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string url = 1;
    public java.lang.String url;

    // optional .common.PImageTagList Tags = 2;
    public com.blemobi.sep.probuf.nano.NewsProtos.PImageTagList tags;

    // optional string thumbnail = 3;
    public java.lang.String thumbnail;

    // optional string des = 4;
    public java.lang.String des;

    public PImage() {
      clear();
    }

    public PImage clear() {
      url = "";
      tags = null;
      thumbnail = "";
      des = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.url.equals("")) {
        output.writeString(1, this.url);
      }
      if (this.tags != null) {
        output.writeMessage(2, this.tags);
      }
      if (!this.thumbnail.equals("")) {
        output.writeString(3, this.thumbnail);
      }
      if (!this.des.equals("")) {
        output.writeString(4, this.des);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.url.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.url);
      }
      if (this.tags != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.tags);
      }
      if (!this.thumbnail.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.thumbnail);
      }
      if (!this.des.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.des);
      }
      return size;
    }

    @Override
    public PImage mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.url = input.readString();
            break;
          }
          case 18: {
            if (this.tags == null) {
              this.tags = new com.blemobi.sep.probuf.nano.NewsProtos.PImageTagList();
            }
            input.readMessage(this.tags);
            break;
          }
          case 26: {
            this.thumbnail = input.readString();
            break;
          }
          case 34: {
            this.des = input.readString();
            break;
          }
        }
      }
    }

    public static PImage parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PImage(), data);
    }

    public static PImage parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PImage().mergeFrom(input);
    }
  }

  public static final class PVideo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PVideo[] _emptyArray;
    public static PVideo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PVideo[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string url = 1;
    public java.lang.String url;

    // optional string img = 2;
    public java.lang.String img;

    // repeated .common.PVideoTag tags = 3;
    public com.blemobi.sep.probuf.nano.NewsProtos.PVideoTag[] tags;

    // optional int64 expires = 4;
    public long expires;

    // optional int32 type = 5;
    public int type;

    public PVideo() {
      clear();
    }

    public PVideo clear() {
      url = "";
      img = "";
      tags = com.blemobi.sep.probuf.nano.NewsProtos.PVideoTag.emptyArray();
      expires = 0L;
      type = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.url.equals("")) {
        output.writeString(1, this.url);
      }
      if (!this.img.equals("")) {
        output.writeString(2, this.img);
      }
      if (this.tags != null && this.tags.length > 0) {
        for (int i = 0; i < this.tags.length; i++) {
          com.blemobi.sep.probuf.nano.NewsProtos.PVideoTag element = this.tags[i];
          if (element != null) {
            output.writeMessage(3, element);
          }
        }
      }
      if (this.expires != 0L) {
        output.writeInt64(4, this.expires);
      }
      if (this.type != 0) {
        output.writeInt32(5, this.type);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.url.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.url);
      }
      if (!this.img.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.img);
      }
      if (this.tags != null && this.tags.length > 0) {
        for (int i = 0; i < this.tags.length; i++) {
          com.blemobi.sep.probuf.nano.NewsProtos.PVideoTag element = this.tags[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(3, element);
          }
        }
      }
      if (this.expires != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(4, this.expires);
      }
      if (this.type != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.type);
      }
      return size;
    }

    @Override
    public PVideo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.url = input.readString();
            break;
          }
          case 18: {
            this.img = input.readString();
            break;
          }
          case 26: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.tags == null ? 0 : this.tags.length;
            com.blemobi.sep.probuf.nano.NewsProtos.PVideoTag[] newArray =
                new com.blemobi.sep.probuf.nano.NewsProtos.PVideoTag[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.tags, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.NewsProtos.PVideoTag();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.NewsProtos.PVideoTag();
            input.readMessage(newArray[i]);
            this.tags = newArray;
            break;
          }
          case 32: {
            this.expires = input.readInt64();
            break;
          }
          case 40: {
            this.type = input.readInt32();
            break;
          }
        }
      }
    }

    public static PVideo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PVideo(), data);
    }

    public static PVideo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PVideo().mergeFrom(input);
    }
  }

  public static final class PAudio extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PAudio[] _emptyArray;
    public static PAudio[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PAudio[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string url = 1;
    public java.lang.String url;

    // optional int32 length = 2;
    public int length;

    // optional int64 expires = 3;
    public long expires;

    public PAudio() {
      clear();
    }

    public PAudio clear() {
      url = "";
      length = 0;
      expires = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.url.equals("")) {
        output.writeString(1, this.url);
      }
      if (this.length != 0) {
        output.writeInt32(2, this.length);
      }
      if (this.expires != 0L) {
        output.writeInt64(3, this.expires);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.url.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.url);
      }
      if (this.length != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.length);
      }
      if (this.expires != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(3, this.expires);
      }
      return size;
    }

    @Override
    public PAudio mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.url = input.readString();
            break;
          }
          case 16: {
            this.length = input.readInt32();
            break;
          }
          case 24: {
            this.expires = input.readInt64();
            break;
          }
        }
      }
    }

    public static PAudio parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PAudio(), data);
    }

    public static PAudio parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PAudio().mergeFrom(input);
    }
  }

  public static final class PImageTagList extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PImageTagList[] _emptyArray;
    public static PImageTagList[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PImageTagList[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .common.PImageTag List = 1;
    public com.blemobi.sep.probuf.nano.NewsProtos.PImageTag[] list;

    public PImageTagList() {
      clear();
    }

    public PImageTagList clear() {
      list = com.blemobi.sep.probuf.nano.NewsProtos.PImageTag.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.NewsProtos.PImageTag element = this.list[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.NewsProtos.PImageTag element = this.list[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public PImageTagList mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.list == null ? 0 : this.list.length;
            com.blemobi.sep.probuf.nano.NewsProtos.PImageTag[] newArray =
                new com.blemobi.sep.probuf.nano.NewsProtos.PImageTag[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.list, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.NewsProtos.PImageTag();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.NewsProtos.PImageTag();
            input.readMessage(newArray[i]);
            this.list = newArray;
            break;
          }
        }
      }
    }

    public static PImageTagList parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PImageTagList(), data);
    }

    public static PImageTagList parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PImageTagList().mergeFrom(input);
    }
  }

  public static final class PImageTag extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PImageTag[] _emptyArray;
    public static PImageTag[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PImageTag[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 Type = 1;
    public int type;

    // optional int32 SubType = 2;
    public int subType;

    // optional float X = 3;
    public float x;

    // optional float Y = 4;
    public float y;

    // optional string Name = 5;
    public java.lang.String name;

    // optional string GoodPrice = 6;
    public java.lang.String goodPrice;

    // optional string GoodLink = 7;
    public java.lang.String goodLink;

    // optional string PersonUuid = 8;
    public java.lang.String personUuid;

    // optional string PersonName = 9;
    public java.lang.String personName;

    public PImageTag() {
      clear();
    }

    public PImageTag clear() {
      type = 0;
      subType = 0;
      x = 0F;
      y = 0F;
      name = "";
      goodPrice = "";
      goodLink = "";
      personUuid = "";
      personName = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.type != 0) {
        output.writeInt32(1, this.type);
      }
      if (this.subType != 0) {
        output.writeInt32(2, this.subType);
      }
      if (java.lang.Float.floatToIntBits(this.x)
          != java.lang.Float.floatToIntBits(0F)) {
        output.writeFloat(3, this.x);
      }
      if (java.lang.Float.floatToIntBits(this.y)
          != java.lang.Float.floatToIntBits(0F)) {
        output.writeFloat(4, this.y);
      }
      if (!this.name.equals("")) {
        output.writeString(5, this.name);
      }
      if (!this.goodPrice.equals("")) {
        output.writeString(6, this.goodPrice);
      }
      if (!this.goodLink.equals("")) {
        output.writeString(7, this.goodLink);
      }
      if (!this.personUuid.equals("")) {
        output.writeString(8, this.personUuid);
      }
      if (!this.personName.equals("")) {
        output.writeString(9, this.personName);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.type != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.type);
      }
      if (this.subType != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.subType);
      }
      if (java.lang.Float.floatToIntBits(this.x)
          != java.lang.Float.floatToIntBits(0F)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeFloatSize(3, this.x);
      }
      if (java.lang.Float.floatToIntBits(this.y)
          != java.lang.Float.floatToIntBits(0F)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeFloatSize(4, this.y);
      }
      if (!this.name.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.name);
      }
      if (!this.goodPrice.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.goodPrice);
      }
      if (!this.goodLink.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.goodLink);
      }
      if (!this.personUuid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.personUuid);
      }
      if (!this.personName.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(9, this.personName);
      }
      return size;
    }

    @Override
    public PImageTag mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.type = input.readInt32();
            break;
          }
          case 16: {
            this.subType = input.readInt32();
            break;
          }
          case 29: {
            this.x = input.readFloat();
            break;
          }
          case 37: {
            this.y = input.readFloat();
            break;
          }
          case 42: {
            this.name = input.readString();
            break;
          }
          case 50: {
            this.goodPrice = input.readString();
            break;
          }
          case 58: {
            this.goodLink = input.readString();
            break;
          }
          case 66: {
            this.personUuid = input.readString();
            break;
          }
          case 74: {
            this.personName = input.readString();
            break;
          }
        }
      }
    }

    public static PImageTag parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PImageTag(), data);
    }

    public static PImageTag parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PImageTag().mergeFrom(input);
    }
  }

  public static final class PVideoTag extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PVideoTag[] _emptyArray;
    public static PVideoTag[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PVideoTag[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional float x = 1;
    public float x;

    // optional float y = 2;
    public float y;

    // optional string text = 3;
    public java.lang.String text;

    public PVideoTag() {
      clear();
    }

    public PVideoTag clear() {
      x = 0F;
      y = 0F;
      text = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (java.lang.Float.floatToIntBits(this.x)
          != java.lang.Float.floatToIntBits(0F)) {
        output.writeFloat(1, this.x);
      }
      if (java.lang.Float.floatToIntBits(this.y)
          != java.lang.Float.floatToIntBits(0F)) {
        output.writeFloat(2, this.y);
      }
      if (!this.text.equals("")) {
        output.writeString(3, this.text);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (java.lang.Float.floatToIntBits(this.x)
          != java.lang.Float.floatToIntBits(0F)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeFloatSize(1, this.x);
      }
      if (java.lang.Float.floatToIntBits(this.y)
          != java.lang.Float.floatToIntBits(0F)) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeFloatSize(2, this.y);
      }
      if (!this.text.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.text);
      }
      return size;
    }

    @Override
    public PVideoTag mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 13: {
            this.x = input.readFloat();
            break;
          }
          case 21: {
            this.y = input.readFloat();
            break;
          }
          case 26: {
            this.text = input.readString();
            break;
          }
        }
      }
    }

    public static PVideoTag parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PVideoTag(), data);
    }

    public static PVideoTag parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PVideoTag().mergeFrom(input);
    }
  }

  public static final class PPostRedpacket extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PPostRedpacket[] _emptyArray;
    public static PPostRedpacket[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PPostRedpacket[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .common.PPostInfo Post = 1;
    public com.blemobi.sep.probuf.nano.NewsProtos.PPostInfo post;

    // optional .common.PSendRedPacket Redpacket = 2;
    public com.blemobi.sep.probuf.nano.WalletProtos.PSendRedPacket redpacket;

    public PPostRedpacket() {
      clear();
    }

    public PPostRedpacket clear() {
      post = null;
      redpacket = null;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.post != null) {
        output.writeMessage(1, this.post);
      }
      if (this.redpacket != null) {
        output.writeMessage(2, this.redpacket);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.post != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.post);
      }
      if (this.redpacket != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(2, this.redpacket);
      }
      return size;
    }

    @Override
    public PPostRedpacket mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.post == null) {
              this.post = new com.blemobi.sep.probuf.nano.NewsProtos.PPostInfo();
            }
            input.readMessage(this.post);
            break;
          }
          case 18: {
            if (this.redpacket == null) {
              this.redpacket = new com.blemobi.sep.probuf.nano.WalletProtos.PSendRedPacket();
            }
            input.readMessage(this.redpacket);
            break;
          }
        }
      }
    }

    public static PPostRedpacket parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PPostRedpacket(), data);
    }

    public static PPostRedpacket parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PPostRedpacket().mergeFrom(input);
    }
  }

  public static final class PRecommendUser extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PRecommendUser[] _emptyArray;
    public static PRecommendUser[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PRecommendUser[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string uuid = 6;
    public java.lang.String uuid;

    // optional string username = 7;
    public java.lang.String username;

    // optional string nickname = 8;
    public java.lang.String nickname;

    // optional string headImgURL = 9;
    public java.lang.String headImgURL;

    // optional int32 gender = 10;
    public int gender;

    // optional int32 membershipLevel = 11;
    public int membershipLevel;

    // optional int32 followship = 12;
    public int followship;

    // optional bool friend = 13;
    public boolean friend;

    public PRecommendUser() {
      clear();
    }

    public PRecommendUser clear() {
      uuid = "";
      username = "";
      nickname = "";
      headImgURL = "";
      gender = 0;
      membershipLevel = 0;
      followship = 0;
      friend = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.uuid.equals("")) {
        output.writeString(6, this.uuid);
      }
      if (!this.username.equals("")) {
        output.writeString(7, this.username);
      }
      if (!this.nickname.equals("")) {
        output.writeString(8, this.nickname);
      }
      if (!this.headImgURL.equals("")) {
        output.writeString(9, this.headImgURL);
      }
      if (this.gender != 0) {
        output.writeInt32(10, this.gender);
      }
      if (this.membershipLevel != 0) {
        output.writeInt32(11, this.membershipLevel);
      }
      if (this.followship != 0) {
        output.writeInt32(12, this.followship);
      }
      if (this.friend != false) {
        output.writeBool(13, this.friend);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.uuid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.uuid);
      }
      if (!this.username.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.username);
      }
      if (!this.nickname.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.nickname);
      }
      if (!this.headImgURL.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(9, this.headImgURL);
      }
      if (this.gender != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(10, this.gender);
      }
      if (this.membershipLevel != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(11, this.membershipLevel);
      }
      if (this.followship != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(12, this.followship);
      }
      if (this.friend != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(13, this.friend);
      }
      return size;
    }

    @Override
    public PRecommendUser mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 50: {
            this.uuid = input.readString();
            break;
          }
          case 58: {
            this.username = input.readString();
            break;
          }
          case 66: {
            this.nickname = input.readString();
            break;
          }
          case 74: {
            this.headImgURL = input.readString();
            break;
          }
          case 80: {
            this.gender = input.readInt32();
            break;
          }
          case 88: {
            this.membershipLevel = input.readInt32();
            break;
          }
          case 96: {
            this.followship = input.readInt32();
            break;
          }
          case 104: {
            this.friend = input.readBool();
            break;
          }
        }
      }
    }

    public static PRecommendUser parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PRecommendUser(), data);
    }

    public static PRecommendUser parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PRecommendUser().mergeFrom(input);
    }
  }

  public static final class PFollowOrFansList extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PFollowOrFansList[] _emptyArray;
    public static PFollowOrFansList[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PFollowOrFansList[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .common.PRecommendUser list = 1;
    public com.blemobi.sep.probuf.nano.NewsProtos.PRecommendUser[] list;

    // optional int32 index = 2;
    public int index;

    public PFollowOrFansList() {
      clear();
    }

    public PFollowOrFansList clear() {
      list = com.blemobi.sep.probuf.nano.NewsProtos.PRecommendUser.emptyArray();
      index = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.NewsProtos.PRecommendUser element = this.list[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      if (this.index != 0) {
        output.writeInt32(2, this.index);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.NewsProtos.PRecommendUser element = this.list[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      if (this.index != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.index);
      }
      return size;
    }

    @Override
    public PFollowOrFansList mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.list == null ? 0 : this.list.length;
            com.blemobi.sep.probuf.nano.NewsProtos.PRecommendUser[] newArray =
                new com.blemobi.sep.probuf.nano.NewsProtos.PRecommendUser[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.list, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.NewsProtos.PRecommendUser();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.NewsProtos.PRecommendUser();
            input.readMessage(newArray[i]);
            this.list = newArray;
            break;
          }
          case 16: {
            this.index = input.readInt32();
            break;
          }
        }
      }
    }

    public static PFollowOrFansList parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PFollowOrFansList(), data);
    }

    public static PFollowOrFansList parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PFollowOrFansList().mergeFrom(input);
    }
  }

  public static final class PPersonStatistic extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PPersonStatistic[] _emptyArray;
    public static PPersonStatistic[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PPersonStatistic[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 friendCnt = 1;
    public int friendCnt;

    // optional int32 followCnt = 2;
    public int followCnt;

    // optional int32 fansCnt = 3;
    public int fansCnt;

    // optional int32 textCnt = 4;
    public int textCnt;

    // optional int32 imageCnt = 5;
    public int imageCnt;

    // optional int32 audioCnt = 6;
    public int audioCnt;

    // optional int32 videoCnt = 7;
    public int videoCnt;

    // optional string CommunityID = 8;
    public java.lang.String communityID;

    public PPersonStatistic() {
      clear();
    }

    public PPersonStatistic clear() {
      friendCnt = 0;
      followCnt = 0;
      fansCnt = 0;
      textCnt = 0;
      imageCnt = 0;
      audioCnt = 0;
      videoCnt = 0;
      communityID = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.friendCnt != 0) {
        output.writeInt32(1, this.friendCnt);
      }
      if (this.followCnt != 0) {
        output.writeInt32(2, this.followCnt);
      }
      if (this.fansCnt != 0) {
        output.writeInt32(3, this.fansCnt);
      }
      if (this.textCnt != 0) {
        output.writeInt32(4, this.textCnt);
      }
      if (this.imageCnt != 0) {
        output.writeInt32(5, this.imageCnt);
      }
      if (this.audioCnt != 0) {
        output.writeInt32(6, this.audioCnt);
      }
      if (this.videoCnt != 0) {
        output.writeInt32(7, this.videoCnt);
      }
      if (!this.communityID.equals("")) {
        output.writeString(8, this.communityID);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.friendCnt != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.friendCnt);
      }
      if (this.followCnt != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.followCnt);
      }
      if (this.fansCnt != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.fansCnt);
      }
      if (this.textCnt != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.textCnt);
      }
      if (this.imageCnt != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.imageCnt);
      }
      if (this.audioCnt != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(6, this.audioCnt);
      }
      if (this.videoCnt != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(7, this.videoCnt);
      }
      if (!this.communityID.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(8, this.communityID);
      }
      return size;
    }

    @Override
    public PPersonStatistic mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.friendCnt = input.readInt32();
            break;
          }
          case 16: {
            this.followCnt = input.readInt32();
            break;
          }
          case 24: {
            this.fansCnt = input.readInt32();
            break;
          }
          case 32: {
            this.textCnt = input.readInt32();
            break;
          }
          case 40: {
            this.imageCnt = input.readInt32();
            break;
          }
          case 48: {
            this.audioCnt = input.readInt32();
            break;
          }
          case 56: {
            this.videoCnt = input.readInt32();
            break;
          }
          case 66: {
            this.communityID = input.readString();
            break;
          }
        }
      }
    }

    public static PPersonStatistic parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PPersonStatistic(), data);
    }

    public static PPersonStatistic parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PPersonStatistic().mergeFrom(input);
    }
  }

  public static final class PNewsUserProfile extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PNewsUserProfile[] _emptyArray;
    public static PNewsUserProfile[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PNewsUserProfile[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional .common.PUser user = 1;
    public com.blemobi.sep.probuf.nano.AccountProtos.PUser user;

    // optional int32 followship = 2;
    public int followship;

    // optional bool friend = 3;
    public boolean friend;

    public PNewsUserProfile() {
      clear();
    }

    public PNewsUserProfile clear() {
      user = null;
      followship = 0;
      friend = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.user != null) {
        output.writeMessage(1, this.user);
      }
      if (this.followship != 0) {
        output.writeInt32(2, this.followship);
      }
      if (this.friend != false) {
        output.writeBool(3, this.friend);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.user != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(1, this.user);
      }
      if (this.followship != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.followship);
      }
      if (this.friend != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(3, this.friend);
      }
      return size;
    }

    @Override
    public PNewsUserProfile mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            if (this.user == null) {
              this.user = new com.blemobi.sep.probuf.nano.AccountProtos.PUser();
            }
            input.readMessage(this.user);
            break;
          }
          case 16: {
            this.followship = input.readInt32();
            break;
          }
          case 24: {
            this.friend = input.readBool();
            break;
          }
        }
      }
    }

    public static PNewsUserProfile parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PNewsUserProfile(), data);
    }

    public static PNewsUserProfile parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PNewsUserProfile().mergeFrom(input);
    }
  }

  public static final class PRelationList extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PRelationList[] _emptyArray;
    public static PRelationList[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PRelationList[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .common.PRelation list = 1;
    public com.blemobi.sep.probuf.nano.NewsProtos.PRelation[] list;

    public PRelationList() {
      clear();
    }

    public PRelationList clear() {
      list = com.blemobi.sep.probuf.nano.NewsProtos.PRelation.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.NewsProtos.PRelation element = this.list[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.NewsProtos.PRelation element = this.list[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public PRelationList mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.list == null ? 0 : this.list.length;
            com.blemobi.sep.probuf.nano.NewsProtos.PRelation[] newArray =
                new com.blemobi.sep.probuf.nano.NewsProtos.PRelation[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.list, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.NewsProtos.PRelation();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.NewsProtos.PRelation();
            input.readMessage(newArray[i]);
            this.list = newArray;
            break;
          }
        }
      }
    }

    public static PRelationList parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PRelationList(), data);
    }

    public static PRelationList parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PRelationList().mergeFrom(input);
    }
  }

  public static final class PRelation extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PRelation[] _emptyArray;
    public static PRelation[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PRelation[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 ship = 1;
    public int ship;

    // optional string uuidA = 2;
    public java.lang.String uuidA;

    // optional string uuidB = 3;
    public java.lang.String uuidB;

    // optional int32 folsA = 4;
    public int folsA;

    // optional int32 fansA = 5;
    public int fansA;

    // optional int32 folsB = 6;
    public int folsB;

    // optional int32 fansB = 7;
    public int fansB;

    public PRelation() {
      clear();
    }

    public PRelation clear() {
      ship = 0;
      uuidA = "";
      uuidB = "";
      folsA = 0;
      fansA = 0;
      folsB = 0;
      fansB = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.ship != 0) {
        output.writeInt32(1, this.ship);
      }
      if (!this.uuidA.equals("")) {
        output.writeString(2, this.uuidA);
      }
      if (!this.uuidB.equals("")) {
        output.writeString(3, this.uuidB);
      }
      if (this.folsA != 0) {
        output.writeInt32(4, this.folsA);
      }
      if (this.fansA != 0) {
        output.writeInt32(5, this.fansA);
      }
      if (this.folsB != 0) {
        output.writeInt32(6, this.folsB);
      }
      if (this.fansB != 0) {
        output.writeInt32(7, this.fansB);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.ship != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.ship);
      }
      if (!this.uuidA.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.uuidA);
      }
      if (!this.uuidB.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.uuidB);
      }
      if (this.folsA != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.folsA);
      }
      if (this.fansA != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.fansA);
      }
      if (this.folsB != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(6, this.folsB);
      }
      if (this.fansB != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(7, this.fansB);
      }
      return size;
    }

    @Override
    public PRelation mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.ship = input.readInt32();
            break;
          }
          case 18: {
            this.uuidA = input.readString();
            break;
          }
          case 26: {
            this.uuidB = input.readString();
            break;
          }
          case 32: {
            this.folsA = input.readInt32();
            break;
          }
          case 40: {
            this.fansA = input.readInt32();
            break;
          }
          case 48: {
            this.folsB = input.readInt32();
            break;
          }
          case 56: {
            this.fansB = input.readInt32();
            break;
          }
        }
      }
    }

    public static PRelation parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PRelation(), data);
    }

    public static PRelation parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PRelation().mergeFrom(input);
    }
  }
}
