// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.blemobi.sep.probuf.nano;

@SuppressWarnings("hiding")
public interface OssProtos {

  public static final class PSts extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PSts[] _emptyArray;
    public static PSts[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PSts[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string accessKeyId = 1;
    public java.lang.String accessKeyId;

    // optional string accessKeySecret = 2;
    public java.lang.String accessKeySecret;

    // optional string securityToken = 3;
    public java.lang.String securityToken;

    // optional string expiration = 4;
    public java.lang.String expiration;

    public PSts() {
      clear();
    }

    public PSts clear() {
      accessKeyId = "";
      accessKeySecret = "";
      securityToken = "";
      expiration = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.accessKeyId.equals("")) {
        output.writeString(1, this.accessKeyId);
      }
      if (!this.accessKeySecret.equals("")) {
        output.writeString(2, this.accessKeySecret);
      }
      if (!this.securityToken.equals("")) {
        output.writeString(3, this.securityToken);
      }
      if (!this.expiration.equals("")) {
        output.writeString(4, this.expiration);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.accessKeyId.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.accessKeyId);
      }
      if (!this.accessKeySecret.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.accessKeySecret);
      }
      if (!this.securityToken.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.securityToken);
      }
      if (!this.expiration.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.expiration);
      }
      return size;
    }

    @Override
    public PSts mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.accessKeyId = input.readString();
            break;
          }
          case 18: {
            this.accessKeySecret = input.readString();
            break;
          }
          case 26: {
            this.securityToken = input.readString();
            break;
          }
          case 34: {
            this.expiration = input.readString();
            break;
          }
        }
      }
    }

    public static PSts parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PSts(), data);
    }

    public static PSts parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PSts().mergeFrom(input);
    }
  }

  public static final class PUpload extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PUpload[] _emptyArray;
    public static PUpload[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PUpload[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bool exists = 1;
    public boolean exists;

    // optional string url = 2;
    public java.lang.String url;

    // repeated string headers = 3;
    public java.lang.String[] headers;

    // optional string objectKey = 4;
    public java.lang.String objectKey;

    public PUpload() {
      clear();
    }

    public PUpload clear() {
      exists = false;
      url = "";
      headers = com.google.protobuf.nano.WireFormatNano.EMPTY_STRING_ARRAY;
      objectKey = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.exists != false) {
        output.writeBool(1, this.exists);
      }
      if (!this.url.equals("")) {
        output.writeString(2, this.url);
      }
      if (this.headers != null && this.headers.length > 0) {
        for (int i = 0; i < this.headers.length; i++) {
          java.lang.String element = this.headers[i];
          if (element != null) {
            output.writeString(3, element);
          }
        }
      }
      if (!this.objectKey.equals("")) {
        output.writeString(4, this.objectKey);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.exists != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(1, this.exists);
      }
      if (!this.url.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.url);
      }
      if (this.headers != null && this.headers.length > 0) {
        int dataCount = 0;
        int dataSize = 0;
        for (int i = 0; i < this.headers.length; i++) {
          java.lang.String element = this.headers[i];
          if (element != null) {
            dataCount++;
            dataSize += com.google.protobuf.nano.CodedOutputByteBufferNano
                .computeStringSizeNoTag(element);
          }
        }
        size += dataSize;
        size += 1 * dataCount;
      }
      if (!this.objectKey.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.objectKey);
      }
      return size;
    }

    @Override
    public PUpload mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.exists = input.readBool();
            break;
          }
          case 18: {
            this.url = input.readString();
            break;
          }
          case 26: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 26);
            int i = this.headers == null ? 0 : this.headers.length;
            java.lang.String[] newArray = new java.lang.String[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.headers, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = input.readString();
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = input.readString();
            this.headers = newArray;
            break;
          }
          case 34: {
            this.objectKey = input.readString();
            break;
          }
        }
      }
    }

    public static PUpload parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PUpload(), data);
    }

    public static PUpload parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PUpload().mergeFrom(input);
    }
  }

  public static final class PDownload extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PDownload[] _emptyArray;
    public static PDownload[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PDownload[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string url = 1;
    public java.lang.String url;

    // optional string thumb = 2;
    public java.lang.String thumb;

    public PDownload() {
      clear();
    }

    public PDownload clear() {
      url = "";
      thumb = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.url.equals("")) {
        output.writeString(1, this.url);
      }
      if (!this.thumb.equals("")) {
        output.writeString(2, this.thumb);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.url.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.url);
      }
      if (!this.thumb.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.thumb);
      }
      return size;
    }

    @Override
    public PDownload mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.url = input.readString();
            break;
          }
          case 18: {
            this.thumb = input.readString();
            break;
          }
        }
      }
    }

    public static PDownload parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PDownload(), data);
    }

    public static PDownload parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PDownload().mergeFrom(input);
    }
  }

  public static final class PUploadArray extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PUploadArray[] _emptyArray;
    public static PUploadArray[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PUploadArray[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .common.PUpload uploads = 1;
    public com.blemobi.sep.probuf.nano.OssProtos.PUpload[] uploads;

    public PUploadArray() {
      clear();
    }

    public PUploadArray clear() {
      uploads = com.blemobi.sep.probuf.nano.OssProtos.PUpload.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.uploads != null && this.uploads.length > 0) {
        for (int i = 0; i < this.uploads.length; i++) {
          com.blemobi.sep.probuf.nano.OssProtos.PUpload element = this.uploads[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.uploads != null && this.uploads.length > 0) {
        for (int i = 0; i < this.uploads.length; i++) {
          com.blemobi.sep.probuf.nano.OssProtos.PUpload element = this.uploads[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public PUploadArray mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.uploads == null ? 0 : this.uploads.length;
            com.blemobi.sep.probuf.nano.OssProtos.PUpload[] newArray =
                new com.blemobi.sep.probuf.nano.OssProtos.PUpload[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.uploads, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.OssProtos.PUpload();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.OssProtos.PUpload();
            input.readMessage(newArray[i]);
            this.uploads = newArray;
            break;
          }
        }
      }
    }

    public static PUploadArray parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PUploadArray(), data);
    }

    public static PUploadArray parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PUploadArray().mergeFrom(input);
    }
  }

  public static final class PDownloadArray extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PDownloadArray[] _emptyArray;
    public static PDownloadArray[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PDownloadArray[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .common.PDownload downloads = 1;
    public com.blemobi.sep.probuf.nano.OssProtos.PDownload[] downloads;

    public PDownloadArray() {
      clear();
    }

    public PDownloadArray clear() {
      downloads = com.blemobi.sep.probuf.nano.OssProtos.PDownload.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.downloads != null && this.downloads.length > 0) {
        for (int i = 0; i < this.downloads.length; i++) {
          com.blemobi.sep.probuf.nano.OssProtos.PDownload element = this.downloads[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.downloads != null && this.downloads.length > 0) {
        for (int i = 0; i < this.downloads.length; i++) {
          com.blemobi.sep.probuf.nano.OssProtos.PDownload element = this.downloads[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public PDownloadArray mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.downloads == null ? 0 : this.downloads.length;
            com.blemobi.sep.probuf.nano.OssProtos.PDownload[] newArray =
                new com.blemobi.sep.probuf.nano.OssProtos.PDownload[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.downloads, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.OssProtos.PDownload();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.OssProtos.PDownload();
            input.readMessage(newArray[i]);
            this.downloads = newArray;
            break;
          }
        }
      }
    }

    public static PDownloadArray parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PDownloadArray(), data);
    }

    public static PDownloadArray parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PDownloadArray().mergeFrom(input);
    }
  }

  public static final class PFileInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PFileInfo[] _emptyArray;
    public static PFileInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PFileInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string digest = 1;
    public java.lang.String digest;

    // optional int32 length = 2;
    public int length;

    // optional string extension = 3;
    public java.lang.String extension;

    public PFileInfo() {
      clear();
    }

    public PFileInfo clear() {
      digest = "";
      length = 0;
      extension = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.digest.equals("")) {
        output.writeString(1, this.digest);
      }
      if (this.length != 0) {
        output.writeInt32(2, this.length);
      }
      if (!this.extension.equals("")) {
        output.writeString(3, this.extension);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.digest.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.digest);
      }
      if (this.length != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.length);
      }
      if (!this.extension.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.extension);
      }
      return size;
    }

    @Override
    public PFileInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.digest = input.readString();
            break;
          }
          case 16: {
            this.length = input.readInt32();
            break;
          }
          case 26: {
            this.extension = input.readString();
            break;
          }
        }
      }
    }

    public static PFileInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PFileInfo(), data);
    }

    public static PFileInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PFileInfo().mergeFrom(input);
    }
  }

  public static final class PFileInfoArray extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PFileInfoArray[] _emptyArray;
    public static PFileInfoArray[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PFileInfoArray[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .common.PFileInfo fileInfos = 1;
    public com.blemobi.sep.probuf.nano.OssProtos.PFileInfo[] fileInfos;

    public PFileInfoArray() {
      clear();
    }

    public PFileInfoArray clear() {
      fileInfos = com.blemobi.sep.probuf.nano.OssProtos.PFileInfo.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.fileInfos != null && this.fileInfos.length > 0) {
        for (int i = 0; i < this.fileInfos.length; i++) {
          com.blemobi.sep.probuf.nano.OssProtos.PFileInfo element = this.fileInfos[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.fileInfos != null && this.fileInfos.length > 0) {
        for (int i = 0; i < this.fileInfos.length; i++) {
          com.blemobi.sep.probuf.nano.OssProtos.PFileInfo element = this.fileInfos[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public PFileInfoArray mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.fileInfos == null ? 0 : this.fileInfos.length;
            com.blemobi.sep.probuf.nano.OssProtos.PFileInfo[] newArray =
                new com.blemobi.sep.probuf.nano.OssProtos.PFileInfo[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.fileInfos, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.OssProtos.PFileInfo();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.OssProtos.PFileInfo();
            input.readMessage(newArray[i]);
            this.fileInfos = newArray;
            break;
          }
        }
      }
    }

    public static PFileInfoArray parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PFileInfoArray(), data);
    }

    public static PFileInfoArray parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PFileInfoArray().mergeFrom(input);
    }
  }
}
