// Generated by the protocol buffer compiler.  DO NOT EDIT!

package com.blemobi.sep.probuf.nano;

@SuppressWarnings("hiding")
public interface WalletProtos {

  public static final class PDiamondTotalCount extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PDiamondTotalCount[] _emptyArray;
    public static PDiamondTotalCount[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PDiamondTotalCount[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 totalVMoney = 1;
    public long totalVMoney;

    public PDiamondTotalCount() {
      clear();
    }

    public PDiamondTotalCount clear() {
      totalVMoney = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.totalVMoney != 0L) {
        output.writeInt64(1, this.totalVMoney);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.totalVMoney != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.totalVMoney);
      }
      return size;
    }

    @Override
    public PDiamondTotalCount mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.totalVMoney = input.readInt64();
            break;
          }
        }
      }
    }

    public static PDiamondTotalCount parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PDiamondTotalCount(), data);
    }

    public static PDiamondTotalCount parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PDiamondTotalCount().mergeFrom(input);
    }
  }

  public static final class PDiamondCount extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PDiamondCount[] _emptyArray;
    public static PDiamondCount[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PDiamondCount[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int64 totalVMoney = 1;
    public long totalVMoney;

    // optional int32 incomeVMoney = 2;
    public int incomeVMoney;

    // optional int32 expendVMoney = 3;
    public int expendVMoney;

    public PDiamondCount() {
      clear();
    }

    public PDiamondCount clear() {
      totalVMoney = 0L;
      incomeVMoney = 0;
      expendVMoney = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.totalVMoney != 0L) {
        output.writeInt64(1, this.totalVMoney);
      }
      if (this.incomeVMoney != 0) {
        output.writeInt32(2, this.incomeVMoney);
      }
      if (this.expendVMoney != 0) {
        output.writeInt32(3, this.expendVMoney);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.totalVMoney != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(1, this.totalVMoney);
      }
      if (this.incomeVMoney != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.incomeVMoney);
      }
      if (this.expendVMoney != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.expendVMoney);
      }
      return size;
    }

    @Override
    public PDiamondCount mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.totalVMoney = input.readInt64();
            break;
          }
          case 16: {
            this.incomeVMoney = input.readInt32();
            break;
          }
          case 24: {
            this.expendVMoney = input.readInt32();
            break;
          }
        }
      }
    }

    public static PDiamondCount parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PDiamondCount(), data);
    }

    public static PDiamondCount parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PDiamondCount().mergeFrom(input);
    }
  }

  public static final class PDiamondInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PDiamondInfo[] _emptyArray;
    public static PDiamondInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PDiamondInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string sid = 1;
    public java.lang.String sid;

    // optional string uuid = 2;
    public java.lang.String uuid;

    // optional string name = 3;
    public java.lang.String name;

    // optional int32 type = 4;
    public int type;

    // optional int32 target = 5;
    public int target;

    // optional string headImgURL = 6;
    public java.lang.String headImgURL;

    // optional int32 vMoney = 7;
    public int vMoney;

    // optional int64 createTime = 8;
    public long createTime;

    public PDiamondInfo() {
      clear();
    }

    public PDiamondInfo clear() {
      sid = "";
      uuid = "";
      name = "";
      type = 0;
      target = 0;
      headImgURL = "";
      vMoney = 0;
      createTime = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.sid.equals("")) {
        output.writeString(1, this.sid);
      }
      if (!this.uuid.equals("")) {
        output.writeString(2, this.uuid);
      }
      if (!this.name.equals("")) {
        output.writeString(3, this.name);
      }
      if (this.type != 0) {
        output.writeInt32(4, this.type);
      }
      if (this.target != 0) {
        output.writeInt32(5, this.target);
      }
      if (!this.headImgURL.equals("")) {
        output.writeString(6, this.headImgURL);
      }
      if (this.vMoney != 0) {
        output.writeInt32(7, this.vMoney);
      }
      if (this.createTime != 0L) {
        output.writeInt64(8, this.createTime);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.sid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.sid);
      }
      if (!this.uuid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.uuid);
      }
      if (!this.name.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.name);
      }
      if (this.type != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.type);
      }
      if (this.target != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.target);
      }
      if (!this.headImgURL.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.headImgURL);
      }
      if (this.vMoney != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(7, this.vMoney);
      }
      if (this.createTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(8, this.createTime);
      }
      return size;
    }

    @Override
    public PDiamondInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.sid = input.readString();
            break;
          }
          case 18: {
            this.uuid = input.readString();
            break;
          }
          case 26: {
            this.name = input.readString();
            break;
          }
          case 32: {
            this.type = input.readInt32();
            break;
          }
          case 40: {
            this.target = input.readInt32();
            break;
          }
          case 50: {
            this.headImgURL = input.readString();
            break;
          }
          case 56: {
            this.vMoney = input.readInt32();
            break;
          }
          case 64: {
            this.createTime = input.readInt64();
            break;
          }
        }
      }
    }

    public static PDiamondInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PDiamondInfo(), data);
    }

    public static PDiamondInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PDiamondInfo().mergeFrom(input);
    }
  }

  public static final class PDiamondInfoList extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PDiamondInfoList[] _emptyArray;
    public static PDiamondInfoList[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PDiamondInfoList[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .common.PDiamondInfo list = 1;
    public com.blemobi.sep.probuf.nano.WalletProtos.PDiamondInfo[] list;

    public PDiamondInfoList() {
      clear();
    }

    public PDiamondInfoList clear() {
      list = com.blemobi.sep.probuf.nano.WalletProtos.PDiamondInfo.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.WalletProtos.PDiamondInfo element = this.list[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.WalletProtos.PDiamondInfo element = this.list[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public PDiamondInfoList mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.list == null ? 0 : this.list.length;
            com.blemobi.sep.probuf.nano.WalletProtos.PDiamondInfo[] newArray =
                new com.blemobi.sep.probuf.nano.WalletProtos.PDiamondInfo[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.list, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.WalletProtos.PDiamondInfo();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.WalletProtos.PDiamondInfo();
            input.readMessage(newArray[i]);
            this.list = newArray;
            break;
          }
        }
      }
    }

    public static PDiamondInfoList parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PDiamondInfoList(), data);
    }

    public static PDiamondInfoList parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PDiamondInfoList().mergeFrom(input);
    }
  }

  public static final class PRedPacketCount extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PRedPacketCount[] _emptyArray;
    public static PRedPacketCount[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PRedPacketCount[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 recvVMoney = 1;
    public int recvVMoney;

    // optional int32 recvCount = 2;
    public int recvCount;

    // optional int32 sendVMoney = 3;
    public int sendVMoney;

    // optional int32 sendCount = 4;
    public int sendCount;

    public PRedPacketCount() {
      clear();
    }

    public PRedPacketCount clear() {
      recvVMoney = 0;
      recvCount = 0;
      sendVMoney = 0;
      sendCount = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.recvVMoney != 0) {
        output.writeInt32(1, this.recvVMoney);
      }
      if (this.recvCount != 0) {
        output.writeInt32(2, this.recvCount);
      }
      if (this.sendVMoney != 0) {
        output.writeInt32(3, this.sendVMoney);
      }
      if (this.sendCount != 0) {
        output.writeInt32(4, this.sendCount);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.recvVMoney != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.recvVMoney);
      }
      if (this.recvCount != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.recvCount);
      }
      if (this.sendVMoney != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.sendVMoney);
      }
      if (this.sendCount != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.sendCount);
      }
      return size;
    }

    @Override
    public PRedPacketCount mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.recvVMoney = input.readInt32();
            break;
          }
          case 16: {
            this.recvCount = input.readInt32();
            break;
          }
          case 24: {
            this.sendVMoney = input.readInt32();
            break;
          }
          case 32: {
            this.sendCount = input.readInt32();
            break;
          }
        }
      }
    }

    public static PRedPacketCount parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PRedPacketCount(), data);
    }

    public static PRedPacketCount parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PRedPacketCount().mergeFrom(input);
    }
  }

  public static final class PRedPacketID extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PRedPacketID[] _emptyArray;
    public static PRedPacketID[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PRedPacketID[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string rid = 1;
    public java.lang.String rid;

    public PRedPacketID() {
      clear();
    }

    public PRedPacketID clear() {
      rid = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.rid.equals("")) {
        output.writeString(1, this.rid);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.rid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.rid);
      }
      return size;
    }

    @Override
    public PRedPacketID mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.rid = input.readString();
            break;
          }
        }
      }
    }

    public static PRedPacketID parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PRedPacketID(), data);
    }

    public static PRedPacketID parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PRedPacketID().mergeFrom(input);
    }
  }

  public static final class PSendRedPacket extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PSendRedPacket[] _emptyArray;
    public static PSendRedPacket[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PSendRedPacket[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string paytoken = 1;
    public java.lang.String paytoken;

    // optional int32 type = 2;
    public int type;

    // optional int32 count = 3;
    public int count;

    // optional int32 vMoney = 4;
    public int vMoney;

    // optional string remark = 5;
    public java.lang.String remark;

    // optional int32 target = 6;
    public int target;

    // optional string targetID = 7;
    public java.lang.String targetID;

    public PSendRedPacket() {
      clear();
    }

    public PSendRedPacket clear() {
      paytoken = "";
      type = 0;
      count = 0;
      vMoney = 0;
      remark = "";
      target = 0;
      targetID = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.paytoken.equals("")) {
        output.writeString(1, this.paytoken);
      }
      if (this.type != 0) {
        output.writeInt32(2, this.type);
      }
      if (this.count != 0) {
        output.writeInt32(3, this.count);
      }
      if (this.vMoney != 0) {
        output.writeInt32(4, this.vMoney);
      }
      if (!this.remark.equals("")) {
        output.writeString(5, this.remark);
      }
      if (this.target != 0) {
        output.writeInt32(6, this.target);
      }
      if (!this.targetID.equals("")) {
        output.writeString(7, this.targetID);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.paytoken.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.paytoken);
      }
      if (this.type != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.type);
      }
      if (this.count != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.count);
      }
      if (this.vMoney != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.vMoney);
      }
      if (!this.remark.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.remark);
      }
      if (this.target != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(6, this.target);
      }
      if (!this.targetID.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.targetID);
      }
      return size;
    }

    @Override
    public PSendRedPacket mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.paytoken = input.readString();
            break;
          }
          case 16: {
            this.type = input.readInt32();
            break;
          }
          case 24: {
            this.count = input.readInt32();
            break;
          }
          case 32: {
            this.vMoney = input.readInt32();
            break;
          }
          case 42: {
            this.remark = input.readString();
            break;
          }
          case 48: {
            this.target = input.readInt32();
            break;
          }
          case 58: {
            this.targetID = input.readString();
            break;
          }
        }
      }
    }

    public static PSendRedPacket parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PSendRedPacket(), data);
    }

    public static PSendRedPacket parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PSendRedPacket().mergeFrom(input);
    }
  }

  public static final class PRedPacketInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PRedPacketInfo[] _emptyArray;
    public static PRedPacketInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PRedPacketInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string sid = 1;
    public java.lang.String sid;

    // optional string rid = 2;
    public java.lang.String rid;

    // optional string uuid = 3;
    public java.lang.String uuid;

    // optional string name = 4;
    public java.lang.String name;

    // optional int32 type = 5;
    public int type;

    // optional int32 target = 6;
    public int target;

    // optional string headImgURL = 7;
    public java.lang.String headImgURL;

    // optional int64 vMoney = 8;
    public long vMoney;

    // optional string remark = 9;
    public java.lang.String remark;

    // optional int64 createTime = 10;
    public long createTime;

    public PRedPacketInfo() {
      clear();
    }

    public PRedPacketInfo clear() {
      sid = "";
      rid = "";
      uuid = "";
      name = "";
      type = 0;
      target = 0;
      headImgURL = "";
      vMoney = 0L;
      remark = "";
      createTime = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.sid.equals("")) {
        output.writeString(1, this.sid);
      }
      if (!this.rid.equals("")) {
        output.writeString(2, this.rid);
      }
      if (!this.uuid.equals("")) {
        output.writeString(3, this.uuid);
      }
      if (!this.name.equals("")) {
        output.writeString(4, this.name);
      }
      if (this.type != 0) {
        output.writeInt32(5, this.type);
      }
      if (this.target != 0) {
        output.writeInt32(6, this.target);
      }
      if (!this.headImgURL.equals("")) {
        output.writeString(7, this.headImgURL);
      }
      if (this.vMoney != 0L) {
        output.writeInt64(8, this.vMoney);
      }
      if (!this.remark.equals("")) {
        output.writeString(9, this.remark);
      }
      if (this.createTime != 0L) {
        output.writeInt64(10, this.createTime);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.sid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.sid);
      }
      if (!this.rid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.rid);
      }
      if (!this.uuid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.uuid);
      }
      if (!this.name.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.name);
      }
      if (this.type != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.type);
      }
      if (this.target != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(6, this.target);
      }
      if (!this.headImgURL.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.headImgURL);
      }
      if (this.vMoney != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(8, this.vMoney);
      }
      if (!this.remark.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(9, this.remark);
      }
      if (this.createTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(10, this.createTime);
      }
      return size;
    }

    @Override
    public PRedPacketInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.sid = input.readString();
            break;
          }
          case 18: {
            this.rid = input.readString();
            break;
          }
          case 26: {
            this.uuid = input.readString();
            break;
          }
          case 34: {
            this.name = input.readString();
            break;
          }
          case 40: {
            this.type = input.readInt32();
            break;
          }
          case 48: {
            this.target = input.readInt32();
            break;
          }
          case 58: {
            this.headImgURL = input.readString();
            break;
          }
          case 64: {
            this.vMoney = input.readInt64();
            break;
          }
          case 74: {
            this.remark = input.readString();
            break;
          }
          case 80: {
            this.createTime = input.readInt64();
            break;
          }
        }
      }
    }

    public static PRedPacketInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PRedPacketInfo(), data);
    }

    public static PRedPacketInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PRedPacketInfo().mergeFrom(input);
    }
  }

  public static final class PSendRedPacketInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PSendRedPacketInfo[] _emptyArray;
    public static PSendRedPacketInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PSendRedPacketInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string uuid = 1;
    public java.lang.String uuid;

    // optional int32 type = 2;
    public int type;

    // optional int32 target = 3;
    public int target;

    // optional int64 vMoney = 4;
    public long vMoney;

    // optional int32 count = 5;
    public int count;

    // optional string remark = 6;
    public java.lang.String remark;

    // optional int64 createTime = 7;
    public long createTime;

    public PSendRedPacketInfo() {
      clear();
    }

    public PSendRedPacketInfo clear() {
      uuid = "";
      type = 0;
      target = 0;
      vMoney = 0L;
      count = 0;
      remark = "";
      createTime = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.uuid.equals("")) {
        output.writeString(1, this.uuid);
      }
      if (this.type != 0) {
        output.writeInt32(2, this.type);
      }
      if (this.target != 0) {
        output.writeInt32(3, this.target);
      }
      if (this.vMoney != 0L) {
        output.writeInt64(4, this.vMoney);
      }
      if (this.count != 0) {
        output.writeInt32(5, this.count);
      }
      if (!this.remark.equals("")) {
        output.writeString(6, this.remark);
      }
      if (this.createTime != 0L) {
        output.writeInt64(7, this.createTime);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.uuid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.uuid);
      }
      if (this.type != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.type);
      }
      if (this.target != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.target);
      }
      if (this.vMoney != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(4, this.vMoney);
      }
      if (this.count != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.count);
      }
      if (!this.remark.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(6, this.remark);
      }
      if (this.createTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(7, this.createTime);
      }
      return size;
    }

    @Override
    public PSendRedPacketInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.uuid = input.readString();
            break;
          }
          case 16: {
            this.type = input.readInt32();
            break;
          }
          case 24: {
            this.target = input.readInt32();
            break;
          }
          case 32: {
            this.vMoney = input.readInt64();
            break;
          }
          case 40: {
            this.count = input.readInt32();
            break;
          }
          case 50: {
            this.remark = input.readString();
            break;
          }
          case 56: {
            this.createTime = input.readInt64();
            break;
          }
        }
      }
    }

    public static PSendRedPacketInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PSendRedPacketInfo(), data);
    }

    public static PSendRedPacketInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PSendRedPacketInfo().mergeFrom(input);
    }
  }

  public static final class PRedPacketInfoList extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PRedPacketInfoList[] _emptyArray;
    public static PRedPacketInfoList[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PRedPacketInfoList[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .common.PRedPacketInfo list = 1;
    public com.blemobi.sep.probuf.nano.WalletProtos.PRedPacketInfo[] list;

    public PRedPacketInfoList() {
      clear();
    }

    public PRedPacketInfoList clear() {
      list = com.blemobi.sep.probuf.nano.WalletProtos.PRedPacketInfo.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.WalletProtos.PRedPacketInfo element = this.list[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.WalletProtos.PRedPacketInfo element = this.list[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public PRedPacketInfoList mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.list == null ? 0 : this.list.length;
            com.blemobi.sep.probuf.nano.WalletProtos.PRedPacketInfo[] newArray =
                new com.blemobi.sep.probuf.nano.WalletProtos.PRedPacketInfo[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.list, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.WalletProtos.PRedPacketInfo();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.WalletProtos.PRedPacketInfo();
            input.readMessage(newArray[i]);
            this.list = newArray;
            break;
          }
        }
      }
    }

    public static PRedPacketInfoList parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PRedPacketInfoList(), data);
    }

    public static PRedPacketInfoList parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PRedPacketInfoList().mergeFrom(input);
    }
  }

  public static final class PRedPacketParticipant extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PRedPacketParticipant[] _emptyArray;
    public static PRedPacketParticipant[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PRedPacketParticipant[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string uuid = 1;
    public java.lang.String uuid;

    // optional string name = 2;
    public java.lang.String name;

    // optional string headImgURL = 3;
    public java.lang.String headImgURL;

    // optional int32 vMoney = 4;
    public int vMoney;

    // optional string remark = 5;
    public java.lang.String remark;

    // optional int64 createTime = 6;
    public long createTime;

    public PRedPacketParticipant() {
      clear();
    }

    public PRedPacketParticipant clear() {
      uuid = "";
      name = "";
      headImgURL = "";
      vMoney = 0;
      remark = "";
      createTime = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.uuid.equals("")) {
        output.writeString(1, this.uuid);
      }
      if (!this.name.equals("")) {
        output.writeString(2, this.name);
      }
      if (!this.headImgURL.equals("")) {
        output.writeString(3, this.headImgURL);
      }
      if (this.vMoney != 0) {
        output.writeInt32(4, this.vMoney);
      }
      if (!this.remark.equals("")) {
        output.writeString(5, this.remark);
      }
      if (this.createTime != 0L) {
        output.writeInt64(6, this.createTime);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.uuid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.uuid);
      }
      if (!this.name.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.name);
      }
      if (!this.headImgURL.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.headImgURL);
      }
      if (this.vMoney != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.vMoney);
      }
      if (!this.remark.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(5, this.remark);
      }
      if (this.createTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(6, this.createTime);
      }
      return size;
    }

    @Override
    public PRedPacketParticipant mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.uuid = input.readString();
            break;
          }
          case 18: {
            this.name = input.readString();
            break;
          }
          case 26: {
            this.headImgURL = input.readString();
            break;
          }
          case 32: {
            this.vMoney = input.readInt32();
            break;
          }
          case 42: {
            this.remark = input.readString();
            break;
          }
          case 48: {
            this.createTime = input.readInt64();
            break;
          }
        }
      }
    }

    public static PRedPacketParticipant parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PRedPacketParticipant(), data);
    }

    public static PRedPacketParticipant parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PRedPacketParticipant().mergeFrom(input);
    }
  }

  public static final class PRedPacketDetail extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PRedPacketDetail[] _emptyArray;
    public static PRedPacketDetail[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PRedPacketDetail[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string rid = 1;
    public java.lang.String rid;

    // optional string uuid = 2;
    public java.lang.String uuid;

    // optional string name = 3;
    public java.lang.String name;

    // optional string headImgURL = 4;
    public java.lang.String headImgURL;

    // optional int32 vMoney = 5;
    public int vMoney;

    // optional int32 status = 6;
    public int status;

    // optional string remark = 7;
    public java.lang.String remark;

    // optional .common.PSendRedPacketInfo info = 8;
    public com.blemobi.sep.probuf.nano.WalletProtos.PSendRedPacketInfo info;

    // repeated .common.PRedPacketParticipant list = 9;
    public com.blemobi.sep.probuf.nano.WalletProtos.PRedPacketParticipant[] list;

    public PRedPacketDetail() {
      clear();
    }

    public PRedPacketDetail clear() {
      rid = "";
      uuid = "";
      name = "";
      headImgURL = "";
      vMoney = 0;
      status = 0;
      remark = "";
      info = null;
      list = com.blemobi.sep.probuf.nano.WalletProtos.PRedPacketParticipant.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.rid.equals("")) {
        output.writeString(1, this.rid);
      }
      if (!this.uuid.equals("")) {
        output.writeString(2, this.uuid);
      }
      if (!this.name.equals("")) {
        output.writeString(3, this.name);
      }
      if (!this.headImgURL.equals("")) {
        output.writeString(4, this.headImgURL);
      }
      if (this.vMoney != 0) {
        output.writeInt32(5, this.vMoney);
      }
      if (this.status != 0) {
        output.writeInt32(6, this.status);
      }
      if (!this.remark.equals("")) {
        output.writeString(7, this.remark);
      }
      if (this.info != null) {
        output.writeMessage(8, this.info);
      }
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.WalletProtos.PRedPacketParticipant element = this.list[i];
          if (element != null) {
            output.writeMessage(9, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.rid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.rid);
      }
      if (!this.uuid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.uuid);
      }
      if (!this.name.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.name);
      }
      if (!this.headImgURL.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.headImgURL);
      }
      if (this.vMoney != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.vMoney);
      }
      if (this.status != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(6, this.status);
      }
      if (!this.remark.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(7, this.remark);
      }
      if (this.info != null) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
          .computeMessageSize(8, this.info);
      }
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.WalletProtos.PRedPacketParticipant element = this.list[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(9, element);
          }
        }
      }
      return size;
    }

    @Override
    public PRedPacketDetail mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.rid = input.readString();
            break;
          }
          case 18: {
            this.uuid = input.readString();
            break;
          }
          case 26: {
            this.name = input.readString();
            break;
          }
          case 34: {
            this.headImgURL = input.readString();
            break;
          }
          case 40: {
            this.vMoney = input.readInt32();
            break;
          }
          case 48: {
            this.status = input.readInt32();
            break;
          }
          case 58: {
            this.remark = input.readString();
            break;
          }
          case 66: {
            if (this.info == null) {
              this.info = new com.blemobi.sep.probuf.nano.WalletProtos.PSendRedPacketInfo();
            }
            input.readMessage(this.info);
            break;
          }
          case 74: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 74);
            int i = this.list == null ? 0 : this.list.length;
            com.blemobi.sep.probuf.nano.WalletProtos.PRedPacketParticipant[] newArray =
                new com.blemobi.sep.probuf.nano.WalletProtos.PRedPacketParticipant[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.list, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.WalletProtos.PRedPacketParticipant();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.WalletProtos.PRedPacketParticipant();
            input.readMessage(newArray[i]);
            this.list = newArray;
            break;
          }
        }
      }
    }

    public static PRedPacketDetail parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PRedPacketDetail(), data);
    }

    public static PRedPacketDetail parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PRedPacketDetail().mergeFrom(input);
    }
  }

  public static final class PWalletGiftTotalCount extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PWalletGiftTotalCount[] _emptyArray;
    public static PWalletGiftTotalCount[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PWalletGiftTotalCount[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 totalCount = 1;
    public int totalCount;

    public PWalletGiftTotalCount() {
      clear();
    }

    public PWalletGiftTotalCount clear() {
      totalCount = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.totalCount != 0) {
        output.writeInt32(1, this.totalCount);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.totalCount != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.totalCount);
      }
      return size;
    }

    @Override
    public PWalletGiftTotalCount mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.totalCount = input.readInt32();
            break;
          }
        }
      }
    }

    public static PWalletGiftTotalCount parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PWalletGiftTotalCount(), data);
    }

    public static PWalletGiftTotalCount parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PWalletGiftTotalCount().mergeFrom(input);
    }
  }

  public static final class PWalletGiftCount extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PWalletGiftCount[] _emptyArray;
    public static PWalletGiftCount[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PWalletGiftCount[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 totalCount = 1;
    public int totalCount;

    // optional int32 recvVMoney = 2;
    public int recvVMoney;

    // optional int32 recvCount = 3;
    public int recvCount;

    // optional int32 sendVMoney = 4;
    public int sendVMoney;

    // optional int32 sendCount = 5;
    public int sendCount;

    public PWalletGiftCount() {
      clear();
    }

    public PWalletGiftCount clear() {
      totalCount = 0;
      recvVMoney = 0;
      recvCount = 0;
      sendVMoney = 0;
      sendCount = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.totalCount != 0) {
        output.writeInt32(1, this.totalCount);
      }
      if (this.recvVMoney != 0) {
        output.writeInt32(2, this.recvVMoney);
      }
      if (this.recvCount != 0) {
        output.writeInt32(3, this.recvCount);
      }
      if (this.sendVMoney != 0) {
        output.writeInt32(4, this.sendVMoney);
      }
      if (this.sendCount != 0) {
        output.writeInt32(5, this.sendCount);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.totalCount != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.totalCount);
      }
      if (this.recvVMoney != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(2, this.recvVMoney);
      }
      if (this.recvCount != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(3, this.recvCount);
      }
      if (this.sendVMoney != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(4, this.sendVMoney);
      }
      if (this.sendCount != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.sendCount);
      }
      return size;
    }

    @Override
    public PWalletGiftCount mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.totalCount = input.readInt32();
            break;
          }
          case 16: {
            this.recvVMoney = input.readInt32();
            break;
          }
          case 24: {
            this.recvCount = input.readInt32();
            break;
          }
          case 32: {
            this.sendVMoney = input.readInt32();
            break;
          }
          case 40: {
            this.sendCount = input.readInt32();
            break;
          }
        }
      }
    }

    public static PWalletGiftCount parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PWalletGiftCount(), data);
    }

    public static PWalletGiftCount parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PWalletGiftCount().mergeFrom(input);
    }
  }

  public static final class PWalletGiftInfo extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PWalletGiftInfo[] _emptyArray;
    public static PWalletGiftInfo[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PWalletGiftInfo[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string sid = 1;
    public java.lang.String sid;

    // optional string uuid = 2;
    public java.lang.String uuid;

    // optional string name = 3;
    public java.lang.String name;

    // optional string headImgURL = 4;
    public java.lang.String headImgURL;

    // optional int32 gid = 5;
    public int gid;

    // optional int32 vMoney = 6;
    public int vMoney;

    // optional int32 count = 7;
    public int count;

    // optional int64 createTime = 8;
    public long createTime;

    public PWalletGiftInfo() {
      clear();
    }

    public PWalletGiftInfo clear() {
      sid = "";
      uuid = "";
      name = "";
      headImgURL = "";
      gid = 0;
      vMoney = 0;
      count = 0;
      createTime = 0L;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.sid.equals("")) {
        output.writeString(1, this.sid);
      }
      if (!this.uuid.equals("")) {
        output.writeString(2, this.uuid);
      }
      if (!this.name.equals("")) {
        output.writeString(3, this.name);
      }
      if (!this.headImgURL.equals("")) {
        output.writeString(4, this.headImgURL);
      }
      if (this.gid != 0) {
        output.writeInt32(5, this.gid);
      }
      if (this.vMoney != 0) {
        output.writeInt32(6, this.vMoney);
      }
      if (this.count != 0) {
        output.writeInt32(7, this.count);
      }
      if (this.createTime != 0L) {
        output.writeInt64(8, this.createTime);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.sid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.sid);
      }
      if (!this.uuid.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(2, this.uuid);
      }
      if (!this.name.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(3, this.name);
      }
      if (!this.headImgURL.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(4, this.headImgURL);
      }
      if (this.gid != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(5, this.gid);
      }
      if (this.vMoney != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(6, this.vMoney);
      }
      if (this.count != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(7, this.count);
      }
      if (this.createTime != 0L) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt64Size(8, this.createTime);
      }
      return size;
    }

    @Override
    public PWalletGiftInfo mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.sid = input.readString();
            break;
          }
          case 18: {
            this.uuid = input.readString();
            break;
          }
          case 26: {
            this.name = input.readString();
            break;
          }
          case 34: {
            this.headImgURL = input.readString();
            break;
          }
          case 40: {
            this.gid = input.readInt32();
            break;
          }
          case 48: {
            this.vMoney = input.readInt32();
            break;
          }
          case 56: {
            this.count = input.readInt32();
            break;
          }
          case 64: {
            this.createTime = input.readInt64();
            break;
          }
        }
      }
    }

    public static PWalletGiftInfo parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PWalletGiftInfo(), data);
    }

    public static PWalletGiftInfo parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PWalletGiftInfo().mergeFrom(input);
    }
  }

  public static final class PWalletGiftInfoList extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PWalletGiftInfoList[] _emptyArray;
    public static PWalletGiftInfoList[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PWalletGiftInfoList[0];
          }
        }
      }
      return _emptyArray;
    }

    // repeated .common.PWalletGiftInfo list = 1;
    public com.blemobi.sep.probuf.nano.WalletProtos.PWalletGiftInfo[] list;

    public PWalletGiftInfoList() {
      clear();
    }

    public PWalletGiftInfoList clear() {
      list = com.blemobi.sep.probuf.nano.WalletProtos.PWalletGiftInfo.emptyArray();
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.WalletProtos.PWalletGiftInfo element = this.list[i];
          if (element != null) {
            output.writeMessage(1, element);
          }
        }
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.list != null && this.list.length > 0) {
        for (int i = 0; i < this.list.length; i++) {
          com.blemobi.sep.probuf.nano.WalletProtos.PWalletGiftInfo element = this.list[i];
          if (element != null) {
            size += com.google.protobuf.nano.CodedOutputByteBufferNano
              .computeMessageSize(1, element);
          }
        }
      }
      return size;
    }

    @Override
    public PWalletGiftInfoList mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            int arrayLength = com.google.protobuf.nano.WireFormatNano
                .getRepeatedFieldArrayLength(input, 10);
            int i = this.list == null ? 0 : this.list.length;
            com.blemobi.sep.probuf.nano.WalletProtos.PWalletGiftInfo[] newArray =
                new com.blemobi.sep.probuf.nano.WalletProtos.PWalletGiftInfo[i + arrayLength];
            if (i != 0) {
              java.lang.System.arraycopy(this.list, 0, newArray, 0, i);
            }
            for (; i < newArray.length - 1; i++) {
              newArray[i] = new com.blemobi.sep.probuf.nano.WalletProtos.PWalletGiftInfo();
              input.readMessage(newArray[i]);
              input.readTag();
            }
            // Last one without readTag.
            newArray[i] = new com.blemobi.sep.probuf.nano.WalletProtos.PWalletGiftInfo();
            input.readMessage(newArray[i]);
            this.list = newArray;
            break;
          }
        }
      }
    }

    public static PWalletGiftInfoList parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PWalletGiftInfoList(), data);
    }

    public static PWalletGiftInfoList parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PWalletGiftInfoList().mergeFrom(input);
    }
  }

  public static final class PWalletPayPwdIsSet extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PWalletPayPwdIsSet[] _emptyArray;
    public static PWalletPayPwdIsSet[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PWalletPayPwdIsSet[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional bool isset = 1;
    public boolean isset;

    public PWalletPayPwdIsSet() {
      clear();
    }

    public PWalletPayPwdIsSet clear() {
      isset = false;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.isset != false) {
        output.writeBool(1, this.isset);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.isset != false) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeBoolSize(1, this.isset);
      }
      return size;
    }

    @Override
    public PWalletPayPwdIsSet mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.isset = input.readBool();
            break;
          }
        }
      }
    }

    public static PWalletPayPwdIsSet parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PWalletPayPwdIsSet(), data);
    }

    public static PWalletPayPwdIsSet parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PWalletPayPwdIsSet().mergeFrom(input);
    }
  }

  public static final class PWalletToken extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PWalletToken[] _emptyArray;
    public static PWalletToken[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PWalletToken[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional string token = 1;
    public java.lang.String token;

    public PWalletToken() {
      clear();
    }

    public PWalletToken clear() {
      token = "";
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (!this.token.equals("")) {
        output.writeString(1, this.token);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (!this.token.equals("")) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeStringSize(1, this.token);
      }
      return size;
    }

    @Override
    public PWalletToken mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 10: {
            this.token = input.readString();
            break;
          }
        }
      }
    }

    public static PWalletToken parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PWalletToken(), data);
    }

    public static PWalletToken parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PWalletToken().mergeFrom(input);
    }
  }

  public static final class PRedPacketStatus extends
      com.google.protobuf.nano.MessageNano {

    private static volatile PRedPacketStatus[] _emptyArray;
    public static PRedPacketStatus[] emptyArray() {
      // Lazily initializes the empty array
      if (_emptyArray == null) {
        synchronized (
            com.google.protobuf.nano.InternalNano.LAZY_INIT_LOCK) {
          if (_emptyArray == null) {
            _emptyArray = new PRedPacketStatus[0];
          }
        }
      }
      return _emptyArray;
    }

    // optional int32 status = 1;
    public int status;

    public PRedPacketStatus() {
      clear();
    }

    public PRedPacketStatus clear() {
      status = 0;
      cachedSize = -1;
      return this;
    }

    @Override
    public void writeTo(com.google.protobuf.nano.CodedOutputByteBufferNano output)
        throws java.io.IOException {
      if (this.status != 0) {
        output.writeInt32(1, this.status);
      }
      super.writeTo(output);
    }

    @Override
    protected int computeSerializedSize() {
      int size = super.computeSerializedSize();
      if (this.status != 0) {
        size += com.google.protobuf.nano.CodedOutputByteBufferNano
            .computeInt32Size(1, this.status);
      }
      return size;
    }

    @Override
    public PRedPacketStatus mergeFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      while (true) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            return this;
          default: {
            if (!com.google.protobuf.nano.WireFormatNano.parseUnknownField(input, tag)) {
              return this;
            }
            break;
          }
          case 8: {
            this.status = input.readInt32();
            break;
          }
        }
      }
    }

    public static PRedPacketStatus parseFrom(byte[] data)
        throws com.google.protobuf.nano.InvalidProtocolBufferNanoException {
      return com.google.protobuf.nano.MessageNano.mergeFrom(new PRedPacketStatus(), data);
    }

    public static PRedPacketStatus parseFrom(
            com.google.protobuf.nano.CodedInputByteBufferNano input)
        throws java.io.IOException {
      return new PRedPacketStatus().mergeFrom(input);
    }
  }
}
